### ISSUE TITLE
Store: WooCommerce: Plugin installation unreliable: Can hang store setup or report false errors

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#15901]
Yesterday I ran through setting up a new store from start to finish.

Store setup hung on the 'Installing plugins' step for 5+ minutes. I had to refresh to get it to work.

[Console](https://cloudup.com/cuPngxxss9k) suggests it was a proxy issue. Thought I'd open this up though for a dev to confirm/deny/investigate.

**Comment by TheSteveK** [comment]
I second this emotion :)  Right now I have 2 test sites hanging during the install process.  Churchofdbaa.com and crashteststeve.com   Churchofdbaa is hanging at 50% while crashtest steve is hanging at 25%.  On that one I hit the back button to see what would happen.  I noticed the WooCommerce plugin was installed in wp-admin.  I deleted the plugin and started the store process again but it's been hanging at 25% for the last 10 minutes or so.  I am not proxied.

**Comment by kellychoffman** [comment]
Westi has this happen and when he went to wp-admin plugins page, he found that plugins were installed but not activated.

**Comment by belcherj** [comment]
#16000 merged which has taken care of part of the problem.  Working on a solution for #16003 

Between these two this issue should be fixed.

**Comment by belcherj** [comment]
@jameskoster @TheSteveK Please retest and close if working.

**Comment by jameskoster** [comment]
Tested on wpcalypso.wordpress.com and it still hangs for me. Console errors;

![errors](https://cldup.com/WQ3zOFogDo.png)

**Comment by jameskoster** [comment]
@allendav @justinshreve @coderkevin @DanReyLop @marcinbot are any of you able to test/confirm please?

**Comment by allendav** [comment]
I just had two plugins silently fail to set up on a freshly created store myself:

<img width="467" alt="screen shot 2017-07-20 at 12 52 58 pm" src="https://user-images.githubusercontent.com/1595739/28436094-96d85342-6d4a-11e7-90bb-bf210c1f139c.png">

By "sliently" I mean that the installation progress bar moved along from 0 to 100% in a few chunks and then I was advanced to the set-your-store-location view, with no errors on the screen but the above errors in the console.

On looking at the site ala wp-admin, it appears that all five plugins were installed and activated, however:

- WooCommerce (I did this already before clicking on the store link - i used this to kick off the AT)
- TaxJar - installed and activated
- WooCommerce API Dev - installed and activated
- WooCommerce Services - installed and activated
- Stripe - installed and activated

I'll write a separate issue to clean up the false errors in the console

**Comment by justinshreve** [comment]
I just went through this on a fresh install too and got some different errors:

<img width="1056" alt="screen shot 2017-07-20 at 1 06 32 pm" src="https://user-images.githubusercontent.com/689165/28436590-4c1bdbc4-6d4c-11e7-9252-377f2ee763fc.png">

It was reporting that `woocommerce-services`was not a valid plugin.

It hung right around 100% -- and this was the results (after I finally closed the tab and checked my installed plugins):

* WooCommerce - Installed & Activated
* TaxJar - Not Installed
* API Dev - Installed & Activated
* WooCommerce Services - Installed but NOT Activated
* Stripe - Installed & Activated

**Comment by belcherj** [comment]
Hmm.  I'm not sure what can be done here other than better error handling and flow control.  Most likely you will need to retry the install.  

I still have no idea why the 'slug' error pops up.  For some reason the function gets called with undefined as the slug.
