### ISSUE TITLE
Sidebar: iphone 6 sidebar view not centered

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#1691]
I noticed this in my real iphone 6 in production, but took the screenshot in chrome's emulated iphone6 because that's easy. The display of the "my-sites" sidebar seems off to me. It's skewed to the right. Whereas the sidebar for all other sections spans the entire width. Not sure where/when this started happening. /cc @rickybanister you're a designer :smile: do you know anything about this?

### my sites
![my-sites-sidebar](https://cloud.githubusercontent.com/assets/134044/11852575/54297d1c-a3fe-11e5-8f61-8cf961ac9e5b.png)

-------------
### reader
![reader sidebar](https://cloudup.com/cAWDlGOuKcb+)

------------
### editor
![editor sidebar](https://cloudup.com/c0c7qoz68mx+)

**Comment by shaunandrews** [comment]
Can confirm. The site picker isn't getting the right width. I believe @mtias made a change there recently.

**Comment by mtias** [comment]
It's fixed here: https://github.com/Automattic/wp-calypso/pull/1588

**Comment by designsimply** [comment]
The fix for #1588 appears to be merged in #1623, but the site picker layout glitch is still happening:

<img alt="img_6025" width="400" src="https://cloud.githubusercontent.com/assets/1119271/11871591/96c91ace-a49e-11e5-80cf-6307a7c1169f.PNG" />
<sup>Seen at https://wordpress.com/ after clicking "Switch Site" using Safari iOS 9.2 on iPhone 6</sup>

**Comment by mtias** [comment]
#1588 is not yet merged.

**Comment by mtias** [comment]
I merged it now.

**Comment by mtias** [comment]
So fixed.
