### ISSUE TITLE
Login OAuth: The WordPress.com button in top right doesn't show WordPress.com

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#17315]
#### Steps to reproduce
1. Starting at URL: gravatar.com or polldaddy.com or woocommerce.com etc. proxied
2. Click Sign in with WordPress.com
3. On the WordPress.com login page click the "WordPress.com" button in the top right

#### What I expected

To see the WordPress.com homepage (as per existing non-proxied behaviour)

#### What happened instead

URL is changed but page remains the same

#### Browser / OS version

Chrome, Safari and Firefox macOS

#### Screenshot / Video

![wp com link](https://user-images.githubusercontent.com/128826/29439021-17a19f3c-83fe-11e7-931e-501cf169fc15.gif)

**Comment by danhauk** [comment]
This should be fixed in #17322. I tested and wasn't able to reproduce this.

**Comment by jsnmoon** [comment]
Hi @danhauk, this issue still occurs on pages like [this (proxied)](https://wordpress.com/log-in?client_id=1854). I have successfully reproduced this issue for both Chrome 60 and Firefox 56.

I have a bugfix for this coming up shortly.

**Comment by danhauk** [comment]
@jsnmoon Sorry, my mistake. I misread the issue and thought it was referring to the display of the button, not the functionality. Carry on!
