### ISSUE TITLE
Store: Setup: (Frequently): Some of your settings could not be retrieved

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#21794]
Add a site to your WordPress.com account, choosing the store flow. After domain registration and purchase, the Building Your Store view will load. Unfortunately, frequently, you also get a "Some of your site settings could not be retrieved" error:

<img width="1423" alt="screen shot 2018-01-24 at 8 40 31 am" src="https://user-images.githubusercontent.com/1595739/35344740-b4edac7a-00e2-11e8-9916-8deb3ff3bac7.png">

After a bit, it will advance to the "Howdy! Ready to start selling?" location view, but that never finishes loading...

<img width="1423" alt="screen shot 2018-01-24 at 8 42 16 am" src="https://user-images.githubusercontent.com/1595739/35344753-bccc5f68-00e2-11e8-8190-c16f2ae68586.png">

unless you hit the "Try again" button

<img width="1424" alt="screen shot 2018-01-24 at 8 44 14 am" src="https://user-images.githubusercontent.com/1595739/35344829-e622acaa-00e2-11e8-9c2a-ebecf640da6c.png">

**Comment by timmyc** [comment]
Related p8yzl4-1dd-p2

**Comment by kamikazeballoon** [comment]
Related: 1726774-hc

**Comment by allendav** [comment]
Easy to reproduce. Add the business plan to a simple site and install any plugin OTHER THAN woocommerce (e.g. install Gutenberg). After that, click on the Store link in the wordpress.com sidebar and you'll get the error.

The root cause is we attempt to fetch settings general for some reason while in that state:

<img width="1437" alt="some-of-your-site-settings" src="https://user-images.githubusercontent.com/1595739/35931859-e58d1c86-0bea-11e8-8534-976296c1bd79.png">

**Comment by ryelle** [comment]
This was fixed in #23748

**Comment by eduardozulian** [comment]
Hey there,

I just tried to set up a new store from scratch (as an attempt to get screenshots for en.support doc pages) and I'm still getting the same error:

<img width="1240" alt="captura de tela 2018-05-31 as 12 45 47" src="https://user-images.githubusercontent.com/1136160/40795789-169823ea-64d1-11e8-8bb6-ea2be3c68a26.png">

I see that the issue was apparently fixed so let me know if there's any extra info I can provide.

**Comment by timmyc** [comment]
@eduardozulian what is the site domain?
