### ISSUE TITLE
Signup: "Add" button too small for some translations

### ISSUE THREAD

**Issue by jenial** [Automattic/wp-calypso#2412]
The `Add` button for domain registration during signup ([code](https://github.com/Automattic/wp-calypso/blob/6c82936f7dca433ceddd6e25908a7505bd038ed6/client/components/domains/domain-registration-suggestion/index.jsx#L30)) is designed to fit the English label, but some locales require more space to fit the longer translation. Abbreviating or replacing with a slightly different meaning word (e.g. "OK") leads to suboptimal results. For example, the translation of `Add` into pt_BR is `Adicionar`, and it gets truncated as a button label.

_EN desktop_ screenshot (the button is sized to fit the English label):
![en_desktop_2b_domain_map_existing_screenshot1449463040688](https://cloud.githubusercontent.com/assets/7637835/12260040/bf4e3530-b919-11e5-8a25-cbc2d001a452.png)

_pt_BR desktop_ screenshot (the translation does not fit on the button):
![br_desktop_2b_domain_map_existing_screenshot1449462731541](https://cloud.githubusercontent.com/assets/7637835/12260077/ea164492-b919-11e5-8b0e-5bd7ee4300fb.png)

_pt_BR tablet_ screenshot_ (the translation does not fit on the button):
![br_tablet_2b_domain_map_existing_screenshot1449462815594](https://cloud.githubusercontent.com/assets/7637835/12260052/cffa28ee-b919-11e5-82fd-14880fd71c28.png)

Can a button width be responsive to fit the translation? Are there other ways we can accommodate longer labels in other locale translations?

**Comment by jenial** [comment]
@akirk: FYI, this is still an issue for signup experience for multiple locales: PT-BR, FR, possibly others.

**Comment by jenial** [comment]
Also need to consider the case when a translation is two words, for example Swedish:
English (the button looks OK)
![en_-_domain_mapping](https://cloud.githubusercontent.com/assets/7637835/13203231/05e618fc-d8bc-11e5-8733-65a73050293b.jpg)
Swedish (the button looks out of place)
![sv_-_map_domain](https://cloud.githubusercontent.com/assets/7637835/13203232/05fa58b2-d8bc-11e5-887b-02f529c084b3.jpg)

**Comment by klimeryk** [comment]
This is a very similar issue to #2417 (fixed by #3189). I've tried using the fix from there (in various ways, including _very_... unreasonable ones), but alas, `flexbox` has defeated me once again :cry: @breezyskies, could you work your magic here too? :bow:

**Comment by breezyskies** [comment]
On my radar, but probably won't get a chance to look at this until after our meetup next week.

**Comment by hoverduck** [comment]
12May16 Bug Scrub

Confirmed this is still an issue:

![screen shot 2016-05-12 at 2 37 43 pm](https://cloud.githubusercontent.com/assets/7233112/15226045/1b65f918-184f-11e6-94f2-a83ac181f447.png)

**Comment by klimeryk** [comment]
@meremagee: perhaps your CSS wizards have the bandwidth to fix this probably simple (but significantly impacting i18n) issue? This component is shared between Signup and Domain Management so we share the damage here 😁 (and my CSS foo is [not strong enough](https://github.com/Automattic/wp-calypso/issues/2412#issuecomment-191976542) to fix this 😞)

**Comment by lancewillett** [comment]
A change is awaiting code review, see #8188
