### ISSUE TITLE
i18n: Add plural variant to strings using timeLapsed variable

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#247]
The variable `%(timeLapsed)s` is used in the following stats string:

> It's been %(timeLapsed)s since {{href}}{{postTitle/}}{{/href}} was published. Here's how the post has performed so far...

Because this variable can have a plural value ("day" or "days"), the string must have singular and plural variations for translation. This allows for different singular and plural translations for languages that translate the string differently depending on that variable's value.

In this case, for example, English always uses the singular "It's been" whether you are talking about 1 day or 10 days. However, other languages may use a plural conjugation when talking about multiple days, as in German:

> "ist ... vergangen" when we're talking about one day|week|month|year (singular) and "sind ... vergangen" when it's more than one day|week|month|year.

As a result, the singular/plural variants have to be provided within a single translated string, for example `ist|sind` in the German translation:

> Seit der Veröffentlichung von {{href}}{{postTitle/}}{{/href}} ist|sind %(timeLapsed)s vergangen. Hier siehst du, wie es dem Beitrag bisher ergangen ist ...

Reported here: https://en.forums.wordpress.com/topic/timelapsed-variable-content

**Comment by nylen** [comment]
I looked into this a bit.  If I'm reading correctly, there's not a simple fix that I can see.  We could change the translated string to include a singular and plural variant, but this wouldn't fix the `timeLapsed` text because it is coming from the `moment` library:  http://momentjs.com/docs/#/displaying/fromnow/

I was not able to find where we localize `moment`'s date behavior, if we do at all.

**Comment by lancewillett** [comment]
@nylen Is it set here? https://github.com/Automattic/wp-calypso/blob/12a30ec54875fa20d1f0251cb08eae787476a208/client/lib/mixins/i18n/index.js#L158

From http://momentjs.com/docs/#/i18n/loading-into-nodejs/

**Comment by hoverduck** [comment]
@rachelmcr I think this is fixed, can you confirm?  My German is rusty (i.e. non-existent), but Google Translate says this looks better:

<img width="699" alt="screen shot 2016-05-05 at 12 34 38 pm" src="https://cloud.githubusercontent.com/assets/7233112/15049765/0dc6677a-12be-11e6-8bf3-1cff7e7783ab.png">

**Comment by rachelmcr** [comment]
It isn't fixed — that string still only provides one translation, instead of a single and plural variant. In German, it's translated always as the plural variant:

https://translate.wordpress.com/projects/wpcom/de/default/?filters[status]=either&filters[original_id]=201613&filters[translation_id]=5679778

Here's an example when `timeLapsed` returns text that would call for a singular variant ("one day"/"ein Tag"):

![screen shot 2016-05-12 at 1 33 55 pm](https://cloud.githubusercontent.com/assets/8658164/15214667/463cabd6-1846-11e6-836c-4686b62f161e.png)

(That also exposes an issue with capitalization, since the `timeLapsed` text appears at the start of the translated sentence.)

It's a complicated issue because the correct variant depends on the value returned for `timeLapsed`.

**Comment by rachelmcr** [comment]
I re-tested this and confirmed it is still an issue.

**Comment by hoverduck** [comment]
#bug-scrub

I haven't learned German in the 7 months since I last looked at this, but I don't think it's fixed.  

@nylen, you looked at this briefly back when @rachelmcr first wrote the issue...have you had any epiphanies since then?  Is there a milestone or project we could stick this on so it gets looked at sooner?
