### ISSUE TITLE
Simple Payments Not Allowed on Plan Although it's a Premium Account

### ISSUE THREAD

**Issue by KristinaKay** [Automattic/wp-calypso#26373]
#### Steps to reproduce
1. Calypso Page Editor for site `https://easyartparties.com/weeones`
2. Add Simple Payment Botton
3. Add images and fill out all information and adding the price and allowing users to purchase multiple quantities of each item
4. Publish

#### What I expected

Items added are available for sale to the public.

#### What happened instead

The error message is displayed to Administrator
```
Your plan doesn't include Simple Payments. Learn more and upgrade.
(Only administrators will see this message.)
```

The Page does not have any Simple Payments for the Public.

### What I Tried ####

- Re-adding the Premium Plan
- Changing the theme
- Creating a new page 

#### Browser / OS version
 Firefrox as a Public Viewer- Unproxy
Google Chrome for SU/SSP

#### Screenshot / Video

**For Admin**
<img width="1145" alt="screen shot 2018-07-29 at 12 54 13 pm" src="https://user-images.githubusercontent.com/33169211/43370136-875b556c-932e-11e8-82f6-e5d41f3f4aff.png">

**Public**: 
<img width="1168" alt="screen shot 2018-07-29 at 12 55 28 pm" src="https://user-images.githubusercontent.com/33169211/43370142-b9361158-932e-11e8-8a9a-41ae8bc76cde.png">

#### Context / Source

I was unable to recreate this issue on my test site but could recreate on user's account. I do think have a work-around

If user agrees, complete the following:

- Create a new site for you with a new Premium Plan
- Export all content from the Old Site to the New Site
- Import all of your posts, pages, media, and comments, etc. to the new site
- Try Simple Payments Again

#manual-testing,
#user-report if applicable: 1311470-zen

**Comment by damiannep** [comment]
I was able to reproduce this issue on my test site (damisplayground.wordpress.com) while not proxied, with a test account. I got the same error.

**Comment by damiannep** [comment]
Update from the user: 

The editor displays the errors when I first open it, but corrects itself after adding a new button. 

#1311470-zen

**Comment by rossanafmenezes** [comment]
User came back via chat and added the following info:

Tried to add a new button I have just tried in Google chrome and internet explore and get the same message.

**Comment by rossanafmenezes** [comment]
https://hud.happychat.io/chat/5274508 forgot to add the link to HC above

**Comment by donalirl** [comment]
Another case reported in #5397356-hc (requires an email follow-up when fixed)

**Comment by rodrigoi** [comment]
@KristinaKay I've been trying to reproduce this and I just can't brake it. Also, https://easyartparties.com/weeones appears to be working as expected. Did you try something else to fix this?

**Comment by rodrigoi** [comment]
@rossanafmenezes @donalirl I'm trying to reproduce this with the information provided and it works fine, and the reported site's button's load correctly (for example, I can see all the buttons on _Prices_ for _THE TRAINERS_).
Any additional steps to reproduce this will be greatly appreciated.

**Comment by damiannep** [comment]
@rodrigoi The buttons work fine on the live site. The issue is in adding buttons in the visual editor.

**Steps to reproduce.** 
1. Go to a page on a live site with Simple Payments buttons
2. Click the link to edit the page
3. Notice that error in the Visual editor
4. Try to add a new button. The error resolves.

The error does not occur occur for me if I access the page to edit it from Calypso.

![simple_payments_error](https://user-images.githubusercontent.com/30090682/43502812-e54dda84-955c-11e8-8536-e2d21d36cf8b.gif)

**Comment by rodrigoi** [comment]
@damiannep thanks for the clarification and sorry for the confusion. Looking into this with this new information ;)

**Comment by rodrigoi** [comment]
@KristinaKay @rossanafmenezes @donalirl @damiannep thanks for the help and the patience with this issue. A fix is ready for review and should be deployed soon. I'll let you know when that's done.

A quick workaround for this would be to go thru Calypso's site menu for posts and pages instead of using the _Edit_ link on the site's frontend.

**Comment by KristinaKay** [comment]
> A quick workaround for this would be to go thru Calypso's site menu for posts and pages instead of using the Edit link on the site's frontend.

Thanks for the quick fix and for looking into it.

**Comment by rodrigoi** [comment]
@KristinaKay @rossanafmenezes @donalirl @damiannep thanks again for the help. A fix has been deployed and everything should be fine from now on when using the _Edit_ link while having SP Products.

**Comment by sarahfg** [comment]
@rodrigoi It looks like this is still an issue on sites with a two year plan. You can see it in action on https://beccygillatt.wordpress.com/courses/

http://cld.wthms.co/TyDHrp

Currently updating the user on this at Zen-1327425 and it was reported in HC- 5261957

**Comment by rodrigoi** [comment]
I'll be closing this for now, since the last report has been fixed by manually adding the plan sticker.

![screen shot 2018-08-22 at 17 07 13](https://user-images.githubusercontent.com/233601/44487936-e32e4680-a62d-11e8-8aef-42087959e17d.png)

For more information about these problems, refer to this P2: p7DVsv-591-p2
