### ISSUE TITLE
Notifications: New WooCommerce order notifications missing

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/wp-calypso#27662]
Reported in two tickets - users state that they no longer see any notifications in Calypso of new WooCommerce orders they have received.

#### Steps to reproduce
1. Check the site that is using WooCommerce on WordPress.com (examples in tickets, listed below) - in this case https://freshorganic2home.com
2. Compare Calypso notifications under ALL tab with orders listed under WP Admin > WooCommerce > Orders
3. Note that the most recent notifications are 24th Sept 2018
4. Note that all orders after 24th Sept do not have a corresponding notification in Calypso
5. Verify that WooCommerce email settings are correct for sending emails to the user (site owner)
6. Verify that Calypso notification settings are correct

#### What I expected
Notifications corresponding to recent orders in the notifications bar.

#### What happened instead
No new notifications for WooCommerce orders.

#### Browser / OS version
Firefox 62.0.2 / Mac OS 10.13.6

#### Screenshot / Video
Notification settings: http://cld.wthms.co/qA7NQn
Last order: http://cld.wthms.co/hotwBT
Orders visible in WP Admin since 24th Sept: http://cld.wthms.co/zFZAun

#### Context / Source

Tickets: 1470462-zen (screenshots above for this user), and 1450614-zen

#anxiety #anxiety-flow
#user-report

**Comment by SiobhyB** [comment]
We also had two reports of this issue in the apps: 1448129-z and 1445476-z

Pinging @alexrford as the lead of Hogsmeade, who introduced this feature in  https://github.com/Automattic/wp-calypso/pull/26600.

**Comment by sophiegyo** [comment]
Just to note - user in my above report confirms they receive email notifications; the notifications just aren't pulling through to Calypso.

**Comment by SiobhyB** [comment]
Two star review on Google Play:

> The weborders from woocommerce used to show in the notifications. Now there is nothing but links to articles about nothing I need to know about. Bring back the new order notifications!

**Comment by liviopv** [comment]
Same pattern on 1469477-zen

**Comment by alexrford** [comment]
@SiobhyB I think that you may have meant to ping @astralbodies.

**Comment by jleandroperez** [comment]
Aaron is on sabbatical. We're tracking it, actually a dotcom issue!. I'm assigning the issue to myself just in case. Thank you all!

**Comment by SiobhyB** [comment]
@alexrford: Ooh, sorry! I intended to ping another Alex with a similar last name to you, but used auto-complete irresponsibly. 🤦‍♀️ The correct team have this on their radar now, though.

**Comment by dmsnell** [comment]
Should be resolved from the server-side as of the deploy of D19287-code.

Should we continue to miss notification please reopen here 😄

**Comment by jleandroperez** [comment]
Thank you Dennis!!!

**Comment by thehenrybyrd** [comment]
@dmsnell it looks like there's still an issue with this - though it's partially fixed. :)

The user in 1448129-z came back to report that they're now getting only one generic notification, rather than individual notifications. According to their description, this notification ("Someone placed ...") will keeps refreshing with each order, rather than stacking up.
Example:
![ordernotif](https://user-images.githubusercontent.com/15107387/46915559-f61e2100-cfb5-11e8-942c-f9b3be6c5d25.png)
In this screenshot, the top notification under "Today" will appear "new" every time a new order is placed.
The most recent "Older than a week" notification was from September 23rd, and there have been 25 orders since then.

Hope that's clear - let me know if I can clarify what the problem is.

**Comment by dmsnell** [comment]
Thanks @thehenrybyrd! We're not going to be sending out a new notification for each order because that's what broke the system when we rolled it out the first time. Right now we have re-establishing _some_ notification of orders by replacing the older notice once it comes in.

In the screenshot we have some old notifications; we won't be removing those, and the new behaviors only apply to new ones.

Before we expand too much we're having to reconsider some assumptions about the notification and alerting system we're building, so it's unlikely we'll have bigger changes any time in the immediate future. Hope this helps!
