### ISSUE TITLE
Gutenberg: (Latest Posts and Archive Block) Block Editor rendering of block showing error in Jetpack Site

### ISSUE THREAD

**Issue by JavonDavis** [Automattic/wp-calypso#28035]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/post
2. Select a Jetpack site
3. Create a new Latest Comments Block or a new Archives block

#### What I expected

Preview of respective block information

#### What happened instead

WP Rest API error message

#### Browser / OS version

Chrome v70
Gutenberg v4.0.0

#### Screenshot / Video

![screen shot 2018-10-23 at 5 20 49 pm](https://user-images.githubusercontent.com/6520461/47394318-16518c80-d6e8-11e8-98ae-67e4f96e01c1.png)
![screen shot 2018-10-23 at 5 21 04 pm](https://user-images.githubusercontent.com/6520461/47394319-16ea2300-d6e8-11e8-9f71-be88d85f51e9.png)

**Comment by gwwar** [comment]
If you were interested in investigating further, looking at the network tab should quickly help identify the type of error here.

**Comment by gwwar** [comment]
I wasn't able to repro for a simple site, can you double check if your site actually has Gutenberg enabled (eg opt-in to the wp-admin try Gutenberg notice):
![screen shot 2018-10-23 at 3 35 24 pm](https://user-images.githubusercontent.com/1270189/47394877-59583380-d6d9-11e8-84ed-18aa200b881e.png)

**Comment by JavonDavis** [comment]
@gwwar you're right... It wasn't activated on the simple site I was using, I'll update the description.

**Comment by gwwar** [comment]
I did verify the issue with Jetpack sites though 👍 Looks like we're hitting:
```
https://public-api.wordpress.com/gutenberg/v1/sites/helpingcat.wpsandbox.me/block-renderer/core/archives?context=edit&post_id=477&_envelope=1
```
```
https://public-api.wordpress.com/gutenberg/v1/sites/helpingcat.wpsandbox.me/block-renderer/core/latest-comments?context=edit&post_id=477&_envelope=1
```

Anything change here @mdawaffe @oskosk? I think that looks path looks correct. D18263-code + pMz3w-927-p2 should have covered these gutenberg endpoints.

**Comment by mdawaffe** [comment]
Weird. I will sort it out on Friday.

**Comment by mdawaffe** [comment]
Should be working as of D19971-code. I really thought this was working before, but I don't see how it ever could have been :(

Note, though, that Calypso is using the `gutenberg/v1/…/block-renderer/` endpoint, which is a Gutenberg 4.0 endpoint.

In Gutenberg 4.1, the endpoint moves to `wp/v2/…/block-renderer/`.

This endpoint change means we can currently only talk to Jetpack sites with Gutenberg 4.0 installed. When we upgrade Calypso to be Gutenberg 4.1 compatible, we'll only be able to talk to Jetpack sites with Gutenberg 4.1 installed. Unless we have some clever Gutenberg-version-aware mapping in place.

**Comment by gwwar** [comment]
@mdawaffe does `https://public-api.wordpress.com/wp/v2/sites/helpingcat.wpsandbox.me/block-renderer/core/latest-comments?context=edit&post_id=495&_envelope=1` look about right? I'm still seeing a 404 response.

**Comment by mdawaffe** [comment]
> @mdawaffe does `https://public-api.wordpress.com/wp/v2/sites/helpingcat.wpsandbox.me/block-renderer/core/latest-comments?context=edit&post_id=495&_envelope=1` look about right? I'm still seeing a 404 response.

WordPress.com currently has Gutenberg 4.0 installed, so it only knows about the `gutenberg/v1/…/block-renderer/` route; there's nothing on WordPress.com that registers the `wp/v2/…/block-renderer/` route.

I believe helpingcat.wpsandbox.me has Gutenberg 4.1.1 installed, which is the opposite: it only knows about the `wp/v2/…/block-renderer/` route; there's nothing on helpingcat.wpsandbox.me that registers the `gutenberg/v1/…/block-renderer/` route.

Once we upgrade to 4.1 on WordPress.com, it should start working.

That doesn't answer the "how should it work" question :)

* Should we support Gutenberg 4.1 sites (Core 5.0 sites) now before we've upgraded to Gutenberg 4.1?
* When we do upgrade to Gutenberg 4.1 (or Core 5.0), should we support Gutenberg 4.0 sites?

**Comment by cecoates** [comment]
1506955-hc with the "Latest posts" block.

**Comment by gwwar** [comment]
Closing this one out
