### ISSUE TITLE
Media Editor: "Sorry, there was a problem loading the image. Please close this editor and try selecting the image again."

### ISSUE THREAD

**Issue by spencerberry** [Automattic/wp-calypso#30053]
This is a recently created issue, likely from a recent PR and is affecting live users, including paying users who cannot change their site icon.

1. In Media, choose an image
2. Choose Edit
3. Edit Image
4. `Sorry, there was a problem loading the image. Please close this editor and try selecting the image again.`

You can get to the same error by uploading a site icon in My Site > Settings

#### What I expected
I would expect the editor to load, or the site icon to upload.

#### What happened instead
This error persists, no matter the route or image.

#### Browser / OS version
Chrome 71.0.3578.98 / MacOS 10.14.2

#### Screenshot / Video
![screen shot 2019-01-09 at 9 51 39 am](https://user-images.githubusercontent.com/1162736/50918208-75c05e00-13f4-11e9-9edc-e3e109c24e19.png)

#### Context / Source
#user-report
#p1547050497062800-slack
#9386701-hc with a followup in #1705026-zen

**Comment by Gilmoursa** [comment]
@guicmazeredo and I both had users coming into chat with this same issue:
User's affected:
9379793-hc
9377761-hc
9383560-hc

**Comment by ashercantrell** [comment]
4742223-hc -- they're trying to edit an image from the media library and are also seeing the same problem.

**Comment by eoinsav** [comment]
User kept seeing this message when trying to update their Site Icon: #9394181-hc

**Comment by wprhunt** [comment]
Have another one here:
6828247-hc

I've suggested having them edit from the wp-admin instead for now as that seems to still be working.

**Comment by arunsathiya** [comment]
I can reproduce as well. It happens only on the `wordpress.com` production environment and not on staging, `wpcalypso` or `horizon`. 

Console throws this error:

```
Access to XMLHttpRequest at 'https://businesstestarunsathiyablog.files.wordpress.com/2019/01/test_test_4-1.jpg?' from origin 'https://wordpress.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by arunsathiya** [comment]
Internal ref: pMz3w-9qA-p2

**Comment by hacchism** [comment]
Have a report here too:

8983615-hc

**Comment by adelineyaw** [comment]
Another report here 9391008-hc (as it was affecting their site icon). As a work around, I've asked the user to update their site icon via Customize > Site Identity

**Comment by sirreal** [comment]
The fix has been deployed. Thanks for the reports, everyone.

**Comment by sirreal** [comment]
I've requested that this flow be added to the full end-to-end test suite:

https://github.com/Automattic/wp-e2e-tests/issues/1769

**Comment by ckmccoy2** [comment]
I see that this issue is closed now, but I just received a report of this error in 9372049-zd. We were able to resolve it by switching the dashboard view to classic, but it was still present when the view was set to default.
