### ISSUE TITLE
Export: Loading indicator misplaced when export button text is long

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#32111]
#### Steps to reproduce 

- Change the WordPress.com interface language to Italiano, if you are on English
- Start with a WordPress.com site
- Visit the export section available on https://wordpress.com/settings/general 
- Click on export button available on the top

#### What is expected 

When the exporter is processing, the loading icon is placed below the button, because there is no space to place it to the left of the button. The button's string is long.

<img width="617" alt="Screenshot 2019-04-08 at 20 10 51" src="https://user-images.githubusercontent.com/18581859/55733445-7be9c900-5a3b-11e9-8641-51d6e3b5a5da.png">

The button also looks a bit pushed to the top, and it does not align with the text on the left.

#### What happens instead 

I feel we might need some sort of design changes here, to implement a consistent experience, irrespective of the language of the Calypso interface. As it can be seen below, the loading icon is to be placed to the left of the button.

<img width="673" alt="Screenshot 2019-04-08 at 20 13 23" src="https://user-images.githubusercontent.com/18581859/55733433-755b5180-5a3b-11e9-86f7-4d0069c781d2.png">

#manual-testing

**Comment by Aurorum** [comment]
I think that this has been resolved now by the Exporter being moved into its own section

**Comment by arunsathiya** [comment]
This is still an issue:

<img width="890" alt="Screenshot 2020-04-17 at 14 44 01" src="https://user-images.githubusercontent.com/18581859/79553348-fa029600-80b9-11ea-9f67-d310fe3f484c.png">

**Comment by arunsathiya** [comment]
Tested again, same issue.
