### ISSUE TITLE
FSE: Title Permalinks are uneditable from FSE flows

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35099]
In the FSE editor, try clicking on the page title, then click on "change permalinks". It's currently not selectable. 

![permalinks](https://user-images.githubusercontent.com/1270189/62387408-58c5b680-b50f-11e9-9eb0-0d2350a66b0d.gif)

**Comment by gwwar** [comment]
I think this one is fixed, going to close out.

**Comment by tbradsha** [comment]
This still appears to be an issue, though the button now says "Edit" instead of "Change Permalinks". Clicking it removes focus from the Page Title "block" (though the sidebar doesn't indicate it's a block), and clicking back on the Page Title jumps down the page.

Chrome 79.0.3945.88 + macOS 10.15.1

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
