### ISSUE TITLE
Customizer: CSS becomes "Additional CSS" in atomic

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36246]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/DOMAIN
2. Go to Design > Customize

#### What I expected
We expect the CSS option in the customizer to be the same text label, and same position in the sidebar, independent whether the site is simple or atomic.

#### What happened instead
"CSS" becomes "Additional CSS" on atomic sites and the position of the item in the customizer is moved to the end of the list

#### Screenshot / Video
Screenshot Simple --  https://cloudup.com/cGiW6GalMlo
Screenshot Atomic -- https://cloudup.com/cCKqTnstEb6

#manual-testing

**Comment by donalirl** [comment]
I was about to make this same request when I discovered it already exists.

Can we get these two paths (Customize → CSS and Customize → Additional CSS) to match to keep the flow consistent? A couple of reasons for making this request:

1. I usually guide all site owners to add CSS under Customize → CSS but that often leads to atomic users coming back with "I can't find that. Is it under Additional CSS?" It would be better if the option was called the same thing on both instances.
2. It's also confusing for simple site owners who are used to one way, but then when they upgrade to Business, the wording changes.

**Comment by simison** [comment]
@jeherve @kraftbj Is this Jetpack files not in sync across the plugin and wpcom?

**Comment by jeherve** [comment]
They're quite out of sync. Jetpack was updated a few years back to migrate to using Core's Custom CSS implementation (that is where "Additional CSS" comes from ), but WordPress.com was never migrated.

Internal reference: p94tqY-2T-p2

A potential quickfix for WordPress.com would be to rename the `jetpack_custom_css ` `WP_Customize_Section` on WordPress.com to "Additional CSS" instead of "CSS". See D40301-code for that. Let me know what you think.

As I noted there, this would also mean that we'd need to update WordPress.com support docs to use the new naming.

**Comment by donalirl** [comment]
>As I noted there, this would also mean that we'd need to update WordPress.com support docs to use the new naming.

I'll handle this part when the time comes. It will be a straightforward update.

**Comment by simison** [comment]
>See D40301-code for that. Let me know what you think.

@jeherve Thanks for a quick fix! Tested and accepted it. 🚢

**Comment by jeherve** [comment]
Fix deployed in r204244-wpcom.

@donalirl I'll let you update the docs? Thank you!

**Comment by kathrynwp** [comment]
@jeherve Could we also make a change to the wording when users do **not** have access to custom CSS (i.e free or Personal plan), as they still see just "CSS."

Example screenshot from a site with Personal plan:

<img width="590" alt="Customizer ‹ KP Main Test site — WordPress com - Mozilla Firefox-1" src="https://user-images.githubusercontent.com/7662449/76625483-b7272e80-650d-11ea-8137-94d37c2081a2.png">

**Comment by jeherve** [comment]
@kathrynwp Should be better as of r204256-wpcom
