### ISSUE TITLE
Domain credit remains used when free domain is cancelled within 96 hours

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#38676]
#### Steps to reproduce
1. Register a new domain using a plan's free domain credit
2. Cancel this domain within 96 hours

#### What I expected

For the domain credit to be freed up, since there is no cost to us if a domain is cancelled within 96 hours.

#### What happened instead

Domain credit remained used even after domain cancellation.

#### Context / Source

#17651139-hc #user-report

**Comment by klimeryk** [comment]
This should be fixed once @eltongo's changes in https://github.com/Automattic/wp-calypso/pull/38266 (and related backend patch) are merged 🙏

**Comment by kriskarkoski** [comment]
The linked PR is now merged. Closing this issue.

**Comment by donalirl** [comment]
This is still happening. It has been for a long time but I just thought to open an issue for it.

A recent example can be seen in #27266077-hc.

Can this be revisited? cc @klimeryk

**Comment by donalirl** [comment]
Seen again at #27056029-hc

**Comment by donalirl** [comment]
Seen at #29736219-hc

**Comment by donalirl** [comment]
Again in #18160726-hc

**Comment by klimeryk** [comment]
cc @Automattic/nomado, is this on your radar? 🙏

**Comment by delputnam** [comment]
Thanks for the ping @klimeryk   I'll add it to our list.

**Comment by kelliepeterson** [comment]
Documenting here: When it is time to do this let's limit this to a single instance *per user* that HEs can override. We don't want to create a situation where this can be abused and cause us more AGP overages.

**Comment by donalirl** [comment]
#33627499-hc
