### ISSUE TITLE
Page Layout Selector: Preview is broken 

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#39198]
I've noticed many page layouts are broken in the preview like below. I was looking at a simple site.

<img width="1608" alt="Screenshot 2020-01-31 at 12 44 40" src="https://user-images.githubusercontent.com/908665/73540869-ea63a180-4428-11ea-81af-d29685c1b0cf.png">

**Steps to reproduce**
* Open a Simple site and add a new page.
* Click one of the page layouts to see the preview. Some of them are fine, but many of them appear broken like the screenshot above.

I briefly looked into it, and [this CSS added for Eventbrite block](https://github.com/Automattic/jetpack/blob/master/extensions/blocks/eventbrite/editor.scss#L15) might be the cause. The selector seems to be too generic and seems to be affecting many other blocks unintentionally. I'll apologize if that's not the case!

**Comment by Copons** [comment]
Nice catch @iamtakashi, that line seems to be the cuprit here.

Though, I've tried disabling it in the browser dev tools, and I've noticed that some blocks end up positioned incorrectly on the left:
<img width="1731" alt="Screenshot 2020-01-31 at 13 16 11" src="https://user-images.githubusercontent.com/2070010/73542145-f866f180-442b-11ea-83d2-6ff2fe6318f9.png">

This seems to be observable with Alves and Barnsbury, although not all the time. 🤔

**Comment by iamtakashi** [comment]
I thought that was fixed through #38884. Maybe a regression?

**Comment by Copons** [comment]
> I thought that was fixed through #38884. Maybe a regression?

Ah, given they are recent fixes, could it be that they haven't been merged into WPCOM yet?

**Comment by creativecoder** [comment]
Noting that [making the Eventbrite block styles more specific](https://github.com/Automattic/jetpack/pull/14540#pullrequestreview-351660536) doesn't seem to resolve this layout issue.


<img width="2032" alt="Screen Shot 2020-01-31 at 11 16 53" src="https://user-images.githubusercontent.com/1699996/73560887-77086280-441d-11ea-84b2-dcafc6fed5ae.png">

**Comment by iamtakashi** [comment]
> Noting that making the Eventbrite block styles more specific doesn't seem to resolve this layout issue.

Yes, that overflowing issue is irrelevant to Eventbrite block style.

**Comment by iamtakashi** [comment]
I can see the issue of the Eventbrite block CSS affecting the preview has been fixed. I'll close this issue.
