### ISSUE TITLE
Themes: No URL Redirect on Sites which don't exist

### ISSUE THREAD

**Issue by sararosso** [Automattic/wp-calypso#4089]
1. Starting at URL: https://wordpress.com/design
2. If you insert any value / site name after the /design (like https://wordpress.com/design/whenihavetime) which does not exist on WordPress.com, it will give you this - note that there's no theme listed for the site.

<img width="943" alt="screen shot 2016-03-16 at 12 16 54 pm" src="https://cloud.githubusercontent.com/assets/4126822/13825688/03ea6de2-eb71-11e5-84f8-337111b40d08.png">

Here's what you'd expect for a site which *does exist*, in this case https://wordpress.com/design/whenihavetime.wordpress.com : 

<img width="1019" alt="screen shot 2016-03-16 at 12 19 33 pm" src="https://cloud.githubusercontent.com/assets/4126822/13825761/5d6b6a74-eb71-11e5-8978-f6694d9adbdf.png">

If instead you access a site which you don't have access to, it will redirect you to http://www.wordpress.com/design

3. If you continue to click around using the URL from step 2 which doesn't exist, it will continue to persist the name and eventually break the experience. I clicked "Switch Site" and picked one of my sites - this page never loads: https://wordpress.com/design/whenihavetime/whenihavetime.com 

<img width="1019" alt="screen shot 2016-03-16 at 12 21 41 pm" src="https://cloud.githubusercontent.com/assets/4126822/13825817/abb9af56-eb71-11e5-8565-75a60d8c7389.png">

**Comment by ockham** [comment]
Possibly fixed by #3453 (?)

**Comment by lancewillett** [comment]
Partially fixed:

1. URL start: https://wordpress.com/design/lancetest556.wordpress.com
2. Manually changed to https://wordpress.com/design/whenihavetime
3. Redirects to https://wordpress.com/design/whenihavetime/lancetest556.wordpress.com — it should drop the middle part, maybe?

![screen shot 2016-04-14 at 11 20 24](https://cloud.githubusercontent.com/assets/66797/14538918/e5559eb4-0232-11e6-805b-9445dabfe7ef.png)

**Comment by lancewillett** [comment]
I think we should close for now — no activity in a few months. For future, feel free to re-open if this comes up again. It's low priority since it assumes someone knowing how to edit a URL to navigate — versus clicking existing links in the UI.
