### ISSUE TITLE
Connections: Instagram avatar and disconnection message

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#41326]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/marketing/connections/[site]
2. Create a new Instagram connection
3. The avatar looks like this:
<img width="1063" alt="Screenshot 2020-04-21 at 15 27 13" src="https://user-images.githubusercontent.com/275961/79877952-c343bd00-83e4-11ea-9722-03f4ea95fe1d.png">
4. Disconnect Instagram
5. The message looks like this:
<img width="582" alt="Screenshot 2020-04-21 at 15 27 02" src="https://user-images.githubusercontent.com/275961/79878010-d22a6f80-83e4-11ea-8bda-9eb3b809786f.png">

#### What I expected
- We should show the correct Avatar
- We should show the correct service name when disconnecting

**Comment by obenland** [comment]
The disconnect message seems to have been fixed with D42122-code.

I could reproduce the missing profile pic. That field was empty in the response from `wpcom/v2/me/connections`. I wonder if we're just not checking the right field to grab it.

**Comment by Robertght** [comment]
I can confirm what @obenland mentioned above, yet the missing profile pic is still an issue.

**Comment by ivan-ottinger** [comment]
~~Turns out that the avatar is missing on other connected services as well; e.g. LinkedIn.
`external_profile_picture` coming from `wpcom/v2/me/connections` is `null` on all services I tried to connect.~~

Update: I didn't have profile picture set on my testing accounts. That is the reason LinkedIn didn't work form me.

---

Code that handles Instagram connection doesn't have any `fetch_profile_picture()` function and therefore no action is taken to obtain the profile picture from Instagram at all.

**Comment by ivan-ottinger** [comment]
Alright. This was a bit of a rabbit hole, but: [Instagram's API](https://developers.facebook.com/docs/instagram-basic-display-api/reference/user) doesn't provide a way to fetch profile picture unfortunately. We can only get the fields like username, ID, etc..

I have created a PR (https://github.com/Automattic/wp-calypso/pull/57900) that displays a Grid icon like this:
![Markup on 2021-11-10 at 13:10:06](https://user-images.githubusercontent.com/25105483/141112876-3377ff55-ba74-4424-89e8-e83990f0ae24.png)

I would say this is much nicer than an empty box we have now.

If Instagram changes their API in the future, we will be able to get the profile picture quite easily. The fetched profile picture would then automatically replace the default Grid icon.
