### ISSUE TITLE
Block Patterns - Tabbing through patterns triggers a toolbar attached to the sidebar.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#44042]
Tabbing through our custom block patterns will trigger a toolbar that is attached to the sidebar inserter.  This does not seem to be reproducible with core patterns and is observed on both 8.3 and edge stickered sites.
* Load into the editor.
* Open the inserter via the "+" button on the top left.
* select the 'patterns' tab.
* "Tab" to cycle down the list of patterns.
* 1/3 of the way down the list or so you should notice a toolbar that has been triggered.

![patterns-toolbar](https://user-images.githubusercontent.com/28742426/87067622-57524300-c1e2-11ea-9527-b7fb24402183.gif)

**Comment by yansern** [comment]
This is because the `<Disabled>` component doesn't prevent `<a>` tags within block preview from being focusable when tabbed over. This also caused block toolbar to activate on the `<a>` elements within the block preview.

**Comment by yansern** [comment]
PR here: https://github.com/WordPress/gutenberg/pull/24397

**Comment by Addison-Stavlo** [comment]
Great catch!  This may also fix https://github.com/Automattic/wp-calypso/issues/44038 as well.  I remember that error being seemingly related to to the pattern having CTA buttons or <a> tags near the top. 🤔

**Comment by razvanpapadopol** [comment]
PR was fixed and included in [Gutenberg 8.8 milestone](https://github.com/WordPress/gutenberg/milestone/127?closed=1). This needs to be retested when the new plugin version lands on edge sites.

**Comment by david-szabo97** [comment]
This PR https://github.com/WordPress/gutenberg/pull/24397 is causing infinite loops for me (keeps adding-removing `tabindex`).
Filed a PR to fix it: https://github.com/WordPress/gutenberg/pull/24935

**Comment by david-szabo97** [comment]
Even after the https://github.com/WordPress/gutenberg/pull/24935 PR this is still happening.
Also, we have a new pattern called `YouTube Embed`. Focus goes into this specific pattern. When tabbing, focus is going through the YouTube iframe's elements.

**Comment by Addison-Stavlo** [comment]
Closing this issue as it seems to have been fixed in Gutenberg.  I am no longer able to repro and tabbing through patterns works as expected regardless of their content.
