### ISSUE TITLE
Reader: definition/glossary hovercards appear to be broken

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#45563]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read/blogs/104373005/posts/2549 (internal users only)

#### What I expected

Definition hovercard displays when hovering over a definition, or is hidden completely.

#### What happened instead

The content from the definition hovercard is show in the post content.

#### Screenshot / Video

<img width="749" alt="Screen Shot 2020-09-11 at 13 45 27" src="https://user-images.githubusercontent.com/17325/92840581-60a39a00-f435-11ea-9160-3c3f22099020.png">
<img width="923" alt="Screen Shot 2020-09-11 at 13 45 53" src="https://user-images.githubusercontent.com/17325/92840591-6305f400-f435-11ea-8411-71ba388ccfc9.png">

**Comment by bluefuton** [comment]
Here's another example in comments:

<img width="803" alt="Screen Shot 2020-09-11 at 15 46 15" src="https://user-images.githubusercontent.com/17325/92855071-fa734300-f445-11ea-8670-8c470bbe745f.png">

**Comment by bluefuton** [comment]
This was a regression and has been fixed on the server side. Discussion in pb6Nl-cQ4-p2.

**Comment by jsnmoon** [comment]
It looks like this is still happening. See https://wordpress.com/read/blogs/2647731/posts/52682 (internal users only).

**Comment by bluefuton** [comment]
@jsnmoon is it possible you have the API sandboxed and haven't done `svn up` lately? I'm not seeing any glossary markup on that particular post 🤔

**Comment by jsnmoon** [comment]
🤦‍♂️ Good catch, false alarm...
