### ISSUE TITLE
Blog Post block > Show More button loads duplicated posts

### ISSUE THREAD

**Issue by kylemcph** [Automattic/wp-calypso#47086]
#### Steps to reproduce:

1. Ensure WordPress.com simple site is set as public
2. Add a blog posts block
3. Toggle `Show "More" Button` on, then toggle `Choose Specific Posts` on.
4. Select the posts you want to display and publish / update page
5. Per #46700 only the amount of posts set to display per Settings > Content Types > Blog Posts will display. 

#### What I expected

The number of posts set to display per Settings > Content Types > Blog Posts will display, with a "Load more posts" button displaying more specified posts.

#### What happened instead

The Load more posts button appears, and duplicates the same posts already displayed when clicked.

#### Screenshot / Video

Blog Posts block Display Settings: 

![](https://d.pr/i/tJlPkH+)
Direct link to image: https://d.pr/i/tJlPkH

Video of live page: https://d.pr/v/IVK5qE

#### Context / Source

Related to #46700 and #47087. User reached out in 24794525-hc about this, follow-up ticket 3457739-zen.

**Comment by kriskorn** [comment]
Chat: #25512654-hc
Ticket: #3475831-zen

**Comment by jeyip** [comment]
It seems like something may have changed between now and when this was posted. @kylemcph Would you mind quickly confirming the issue again? I might be missing something, but it appears as if the load more posts button is no longer displayed when we are only showing specific posts.

<img width="691" alt="Screen Shot 2020-11-18 at 12 39 17 PM" src="https://user-images.githubusercontent.com/5414230/99585645-74223280-299b-11eb-9385-cd89162da116.png">

**Comment by kylemcph** [comment]
Hey @jeyip! 

>it appears as if the load more posts button is no longer displayed when we are only showing specific posts.

Yes, you are correct. The `Show "More" button` does not display when `Choose Specific Posts` is toggled on. 

However, if the `Show "More" button` is toggled on **before** toggling on `Choose Specific Posts`, then the live site will display the "Load More Posts" button. The issue is if that combination is selected the "Load More Posts" button will load the already displayed posts. 

Here's a video to show what I mean: 

https://d.pr/v/Ik3HzY

---


I just double-checked and if you replicate my steps to reproduce in the exact order from above, you should see this as well. Make sure that the amount of specific posts chosen is greater than the number of blog posts set to display per page on My Sites > Manage > Settings > Writing > Content types.

**Comment by david-szabo97** [comment]
Proposed two PRs to fix this: https://github.com/Automattic/newspack-blocks/pull/640 https://github.com/Automattic/newspack-blocks/pull/641

**Comment by cathymcbride** [comment]
@kylemcph Can you repro? Looks like this should be fixed?

**Comment by david-szabo97** [comment]
> @kylemcph Can you repro? Looks like this should be fixed?

I can still reproduce it. It won't be fixed until a new Editing Toolkit version is released with the latest newspack blocks version. Right now we have a blocker that prevents us from releasing new newspack blocks version in the editing toolkit.

**Comment by cathymcbride** [comment]
@david-szabo97 What is the blocker?

**Comment by david-szabo97** [comment]
@cathymcbride Here is the tracking issue: https://github.com/Automattic/wp-calypso/issues/48253

**Comment by simison** [comment]
@Copons @tjcafferkey looks like this is ready to go now that blockers are sorted (https://github.com/Automattic/wp-calypso/issues/48253).

**Comment by cathymcbride** [comment]
@kylemcph can you see if you can still repro this?

**Comment by kylemcph** [comment]
@cathymcbride I am not able to replicate. This appear to be fixed. 🎉

**Comment by cathymcbride** [comment]
Woo! Closing!
