### ISSUE TITLE
New post notification emails have a broken image for the site icon

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#48023]
Observed using Gmail/Google Workplace email in particular, new post notification emails do not include the site icon, rather a broken image. 

#### Steps to reproduce

1. Publish a new post on a simple site

2. Check out the email post notification in Gmail

#### What I expected

The site icon to appear on the email:

![aAClTr](https://user-images.githubusercontent.com/39252765/101097534-92cd1f80-357e-11eb-9bd0-fac51d54a1d6.png) 

#### What happened instead

The site icon appears as a broken image:

![DuihVm](https://user-images.githubusercontent.com/39252765/101097550-9c568780-357e-11eb-8177-bd4a8c1c8927.png)

#### Context / Source

User in 3542946-zen noted this started with:

> Every email since 11/27. About 8 emails in total.

The same has been observed with test emails from other HE's. For example:

<img width="778" alt="Markup 2020-12-04 at 09 57 58" src="https://user-images.githubusercontent.com/39252765/101097658-d031ad00-357e-11eb-8613-2c0ab9caf250.png">

**Comment by mlaetitia** [comment]
Just noting here that could be related to this: https://github.com/Automattic/p2/issues/1327
but this one seems to have been fixed back in November. 

Additionally I tested this today and it's working on my premium site.

**Comment by metabreakr** [comment]
I'll have to test this with a couple other sites. In the meantime, this issue still occurs with my team P2:

<img width="617" alt="Screen Shot 2021-01-08 at 7 48 30 AM" src="https://user-images.githubusercontent.com/39252765/104028475-0073f900-5186-11eb-99c7-9580e0885f78.png">

**Comment by kriskarkoski** [comment]
@jonnyruzek Could you copy the URL of the broken image and share it here to see if that points to a particular cause?

**Comment by metabreakr** [comment]
@kriskarkoski 

```
https://ci4.googleusercontent.com/proxy/LmbBrrmTLKVKqTXWiUzvyRCUgLUvl3U_snj8Q5caoNfI_PW56GUk6PwpAZZgcrI5ig07CUPXRFrXDMQi5wll2kZvVvUqAi6nD0uOsgE7EqrJEKKMBsF2=s0-d-e1-ft#https://beakerp2.files.wordpress.com/2017/09/cropped-beaker.png?w=60
```

**Comment by ClassicRKR27** [comment]
Looks like we may have another case here: 5202760-zd-woothemes

Previous HE that worked on this can replicate it.

It looks like it's possible that [uploading a new site icon will resolve the issue](p1651803115606519/1651800488.409089-slack-C03TY6J1A), I'm suggesting that to the user.
