### ISSUE TITLE
Editor: Include help documentation for formatting shortcuts

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#4829]
Our post editor Help dialog does not include information about formatting shortcuts available for use.

| Calypso | wp-admin |
| --- | --- |
| ![calypso help](https://cloud.githubusercontent.com/assets/1779930/14615007/aad9dfce-0571-11e6-9a0e-000fba992246.png) | ![wp-admin help](https://cloud.githubusercontent.com/assets/1779930/14615028/caf60c9c-0571-11e6-91e4-f1a3538de73a.png) |

We should seek to bring these help suggestions to the Calypso editor.

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

Tested with Firefox 57.0.1 on macOS 10.13.2 and confirmed this is still an issue.

**Comment by andfinally** [comment]
Hi @designsimply I've addressed this in https://github.com/Automattic/wp-calypso/pull/22970.

**Comment by andfinally** [comment]
Hi @designsimply, I've created https://github.com/Automattic/wp-calypso/pull/22972 for this.

**Comment by marekhrabe** [comment]
#22972 is definitely a step in a good direction but I still see some room for improvement. First, the help text doesn't fully reflect the functionality. 

> Formatting shortcuts, key, then Enter:

"Key" in this case means typing `>` but also `---` or `####` - that's not really a _key_ anymore. The worst part is that typing `####` and hitting enter doesn't work. No heading will be created unless you also put some text between typing the shortcut and hitting enter. Like `#### Heading<ENTER>`

This is can be pretty confusing and our help doesn't clear it up. Can we maybe come up with something more clever in design team? Adding a tag for design review. 

One more thing I noticed is that there is no way to tell the window is scrollable. Without focusing on the bottom edge, I wouldn't notice there is the fadeout. In my resolution everything looks "just perfect" - the bottom table line is not broken, no text is half visible and thanks to the fadeout, it actually looks like there is just margin between the table and the modal toolbar. No scrolling clue.

<img width="1028" alt="screen shot 2018-03-20 at 10 52 08" src="https://user-images.githubusercontent.com/156676/37663775-3d352a8e-2c5a-11e8-9aa9-fc3d1290ca5f.png">

As this help got pretty big, what about adding tabs or something similar?

**Comment by andfinally** [comment]
Thanks Marek - I've hopefully fixed the wording issues you identified in https://github.com/Automattic/wp-calypso/pull/22972, and I've split the design comments out into a new issue https://github.com/Automattic/wp-calypso/issues/23659.

**Comment by andfinally** [comment]
https://github.com/Automattic/wp-calypso/pull/22972 with the added info has now been merged, and Marek's points have been outlined in https://github.com/Automattic/wp-calypso/issues/23659, so I'm assuming it's safe to close this issue.
