### ISSUE TITLE
Atomic: Manage Plugins menu item looks off for Atomic sites

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#49127]
#### Steps to reproduce the behavior

1. Visit the Calypso dashboard on a WordPress.com Atomic site.
2. The location of the Manage Plugins link is above My Home rather than under Appearance
3. The icon is black rather than light gray

#### What I expected to happen

The Manage Plugins link would appear under Appearance, and the icon would match the other icons.

#### What actually happened

<img width="306" alt="Screen Shot 2021-01-21 at 10 39 20 AM" src="https://user-images.githubusercontent.com/2124984/105377007-58741c00-5bd8-11eb-84b8-411b958b1a46.png">

### Browser / OS version
Chrome 87, Mac OS Catalina 10.15

### Does this happen on simple or atomic sites or both?

Only Atomic sites.

### Is there any console output or error text?

None that I can see.

### Level of impact (Does it block purchases? Does it affect more than just one site?)

Appears to happen for all my Atomic test sites.

**Comment by obenland** [comment]
Oh, that looks like a Calypsoify bug, nice job finding that one!

I was able to replicate it. Looking for a fix

**Comment by obenland** [comment]
I think this should be fixed with https://github.com/Automattic/jetpack/pull/18328. Could you try [activating Jetpack beta](https://jetpack.com/download-jetpack-beta/) on your atomic site and setting it to "Bleeding Edge" to double-check?

**Comment by sixhours** [comment]
<img width="291" alt="Screen Shot 2021-01-21 at 2 40 29 PM" src="https://user-images.githubusercontent.com/2124984/105403332-9e3fdd00-5bf6-11eb-9e6c-e4a308a7c69d.png">

All better with Jetpack Beta and the alpha release. :D

**Comment by davipontesblog** [comment]
Reopening this one as the Jetpack update hasn't been merged to WoA yet, so the issue persists.

**Comment by obenland** [comment]
Tickets usually get closed when the fix for them gets committed, even if they're not released yet. I understand it can feel like there's something missing when the bug is encountered after, but it keeps us from having to go back and bulk-close tickets after a release.

**Comment by mmtr** [comment]
This should be fixed now that Jetpack 9.4 is out.
