### ISSUE TITLE
Nav Unification: Atomic - WordAds Unification/WordAds ad placement links need updating.

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#49144]
This is for Atomic sites only.

### Steps to reproduce the behavior

1. Go to Tools - Earn - View Ad Dashboard - Settings - Manage Ad Placements:
![image](https://user-images.githubusercontent.com/30731356/105397777-5610c280-5bd6-11eb-91b8-df5e5e5c1cc8.png)

2. It will take you to Tools - Marketing - Traffic, which gives only two options for adjusting ad placements:
![image](https://user-images.githubusercontent.com/30731356/105397832-69bc2900-5bd6-11eb-9b94-b84ec799b58e.png)

3. On Atomic, though, actual ad placement settings are in a different spot. There's a weird workflow on this one, since if you're starting on a Calypso page, these settings will be hidden. To view that, click on Jetpack first, and you'll only have access to Activity Log and Backup.
![image](https://user-images.githubusercontent.com/30731356/105397962-94a67d00-5bd6-11eb-8375-a2ccea886282.png)

4. Actual Atomic WordAds settings though, are located under Plugins (to get to WP-Admin) - Jetpack - Settings - Traffic:
![image](https://user-images.githubusercontent.com/30731356/105398041-b0aa1e80-5bd6-11eb-87f1-16a431f140a4.png)

#### What I expected to happen
We need to somehow unify ad options on Atomic. On simple sites, all of the options are under Tools - Earn - View Ad Dashboard - Settings. On Atomic, they're under WP-Admin - Jetpack - Settings - Traffic.

#### What actually happened
A few things:

1. The ad placements options link under Calypso by default is limited, and doesn't include the full suite of customization.
2. Jetpack settings are hidden by default in the OG Calypso menu, and you need to click on Plugins to activate them.
3. The link on Atomic under Tools - Earn - View Ad Dashboard - Settings - Manage Ad Placements needs to go to the Jetpack view (Atomic only), under Plugins (to get to WP-Admin) - Jetpack - Settings - Traffic, OR
4. (3 above, or) The ad placements settings under  Jetpack - Settings - Traffic need to be relocated into Calypso, under  Tools - Earn - View Ad Dashboard - Settings (like on Simple).

### Context
This has been a longstanding issue made worse/more apparent by nav unification, since Jetpack settings are now hidden by default.

Original P2: p9tZKH-7Y-p2

#### Browser / OS version
All.
#### Is this specific to the applied theme? Which one?
All.
#### Does this happen on simple or atomic sites or both?
Atomic.
#### Is there any console output or error text?
No.
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It affects all WordAds users.

**Comment by obenland** [comment]
Yeah this will be one of the tougher cases. 

It'll likely be alleviated a little by 577-gh-Automattic/wpcomsh, since it should sync more of the Jetpack submenu items over. So far we're not ultimately determined what that Jetpack submenu should look like.

@jeherve Do you have thoughts/opinions here? Or can think of someone who does?
Also pinging @lcollette and @sfougnier for their input

**Comment by jeherve** [comment]
That's a tough one indeed.

The existing Marketing / Traffic page in Calypso does have additional ad options. Maybe we should surface that page in Calypso, by adding it to the existing Tools menu?

The settings would then be accessible in two places:
- in the Jetpack menu once 577-gh-Automattic/wpcomsh is resolved
- under Tools > Traffic

**Comment by jeherve** [comment]
> The existing Marketing / Traffic page in Calypso does have additional ad options. Maybe we should surface that page in Calypso, by adding it to the existing Tools menu?

I created #49187 to track other ways one has to get to that Calypso page at the moment, so I definitely think it needs its place in the new Calypso nav.

**Comment by getdave** [comment]
@scosgro Would you be able to re-rest this one for us. We believe it should now be fixed.

**Comment by scosgro** [comment]
> 
> 
> @scosgro Would you be able to re-rest this one for us. We believe it should now be fixed.

On Atomic:

I'm still seeing, under Tools - Earn - View Ad Dashboard - Settings:

![image](https://user-images.githubusercontent.com/30731356/110537684-daac9700-80d7-11eb-9575-31eabaa44de4.png)

The Manage Ad Placements link goes to Tools - Marketing - Traffic, which only has two options for adjusting ad placements:

![image](https://user-images.githubusercontent.com/30731356/110537768-f6b03880-80d7-11eb-8c62-81285ed0710a.png)

While the full WordAds placement settings are under Jetpack - Settings - Traffic:

![image](https://user-images.githubusercontent.com/30731356/110537820-0e87bc80-80d8-11eb-9e46-9adf4bb176f4.png)

On a Simple Site, they're all under Tools - Earn - View Ad Dashboard - Settings:

![image](https://user-images.githubusercontent.com/30731356/110537907-2e1ee500-80d8-11eb-8fea-ccddb6c6f0bb.png)

**Comment by obenland** [comment]
Related: #36331

**Comment by sixhours** [comment]
To confirm, to reduce confusion we're going to remove the Tools -> Marketing -> Traffic -> Ads section on Atomic sites, ref: https://github.com/Automattic/wp-calypso/issues/36331#issuecomment-793026870
