### ISSUE TITLE
Plugins / i18n: Star rating label doesn't handle singular form

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5002]
Steps to reproduce:

1. Set your interface to French.
2. Go to https://wordpress.com/plugins/akismet
3. Check the rating box:

![screen shot 2016-04-26 at 12 03 30 pm](https://cloud.githubusercontent.com/assets/426388/14814521/ee29aaf8-0ba6-11e6-83ee-6c5547462858.png)

"1 star" should be singular:
https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/plugins/plugin-ratings/index.jsx#L54

**Comment by jeherve** [comment]
Also pictured on this screenshot: #4981 (non-English thousands separators are showing as HTML entity)

**Comment by timmyc** [comment]
Should be fixed up now - see #4981

**Comment by jeherve** [comment]
The issue reported in this issue (Star rating label doesn't handle singular form) isn't fixed yet.

**Comment by timmyc** [comment]
sorry about that @jeherve - I had just assumed this issue was around the thousands separator.

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an issue:
<img width="206" alt="screen shot 2016-07-25 at 2 24 02 pm" src="https://cloud.githubusercontent.com/assets/7233112/17112299/84c96c2e-5273-11e6-9824-3f9861882c6b.png">
