### ISSUE TITLE
Gutenberg: v10.2.x plugin upgrade

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#50775]
Previous upgrade: https://github.com/Automattic/wp-calypso/issues/50323
Release notes: [v10.2.0](https://href.li/?https://github.com/WordPress/gutenberg/releases/tag/v10.2.0), [v10.2.1](https://github.com/WordPress/gutenberg/releases/tag/v10.2.1)

### Process

- [x] Install and activate
  - [x] Copy & install v10.2.0-rc.1 (D58493-code, D58494-code)
  - [x] Activate v10.2.0-rc.1 on edge (D58496-code)
  - [x] Copy & install v10.2.0 (D58949-code, D58951-code)
  - [x] Activate v10.2.0 on edge (D58952-code)
  - [x] Activate v10.2.0 on production (D58502-code)
  - [x] Request v10.2.0 update for Atomic sites
  - [x] Copy & install v10.2.1 (D59033-code, D59034-code)
  - [x] Activate v10.2.1 on edge (D59035-code)
  - [x] Activate v10.2.1 on production (D59036-code)
  - [x] Request v10.2.1 update for Atomic sites (p9o2xV-1k3-p2)

- [x] Testing
  - [x] Calypso E2E
    - [x] v10.2.0 (https://github.com/Automattic/wp-calypso/pull/50967)
    - [x] v10.2.1 (https://github.com/Automattic/wp-calypso/pull/51223)
  - [x] Team City (D58502-code)
    - [x] v10.2.0 (D58502-code)
    - [x] v10.2.1 (D59036-code)
- [x] Publish internal announcements (p7DVsv-aU5-p2, p1616027263013800-slack-CB0B2G43X)
- [ ] Clean up unused releases
  - [x] v10.0.2 (D58957-code)
  - [x] v10.1.0 (D58960-code)
  - [x] v10.2.0-rc.1 (D58956-code)
  - [ ] v10.2.0
- [x] Add log entry to the Gutenberg Upgrade Log [pcoGjb-g-p2]
- [x] Open a new issue for the next upgrade, transfer remaining tasks
- [x] Close this issue.

### Issues / Blockers 🐛 

- [ ] Classic: Infinite content duplication loop when wrapping with anchor tag [#29338](https://github.com/WordPress/gutenberg/issues/29338) (not a blocker)
  - Reported in: p1613735197155300/1613458151.107400-slack-CBTN58FTJ 

- [ ] Reusable block can't be broken down into individual blocks, no specific root cause identified yet. Seems specific to using some blocks inside the reusable block, though it's not known yet at this time. (edge case / not a blocker)
  - Reported in: p1614866772382300-slack-C7YPUHBB2

- [ ] Search block's button padding is broken
  - Reported here: https://github.com/WordPress/gutenberg/issues/29952

- [x] Button padding not calculating
  - Reported in: https://github.com/WordPress/gutenberg/issues/29675
  - Slack context: p1615317097008400-slack-C7YPUHBB2
  - Fixed in: https://github.com/WordPress/gutenberg/pull/29554.

- [x] Button gradients support missing
  - Reported in: p1616071125022000-slack-CBTN58FTJ
  - Fixed in: https://github.com/WordPress/gutenberg/pull/29980 (included in v10.2.1)

- [ ] Default font for non-FSE themes missing
  - Reported in https://github.com/Automattic/themes/issues/3280
  - Hotfixed on Simple sites via D59109-code
  - Slack context: p1616412181032500-slack-C7YPUHBB2

---
FYI: @Automattic/team-calypso

**Comment by simison** [comment]
This broken search block padding looks like the issue that's fixed in this release, right? If so, I won't bother opening issue for it:

Twenty Twenty One theme:
<img width="850" alt="Screenshot 2021-03-11 at 10 48 47" src="https://user-images.githubusercontent.com/87168/110761343-4e75ad80-8258-11eb-8b2f-22da8f54aa48.png">

Blank canvas theme:
<img width="174" alt="Screenshot 2021-03-11 at 10 17 13" src="https://user-images.githubusercontent.com/87168/110761368-559cbb80-8258-11eb-8dd6-03a2d29e593e.png">

**Comment by fullofcaffeine** [comment]
@simison Seems it's still present. I tested with both themes on edge and I still see the problem on 10.2.0. I'll do some testing locally and create an issue.

**Comment by fullofcaffeine** [comment]
This is done. Next one: https://github.com/Automattic/wp-calypso/issues/51161.

**Comment by fullofcaffeine** [comment]
> This broken search block padding looks like the issue that's fixed in this release, right? If so, I won't bother opening issue for it:
> 
> Twenty Twenty One theme:
> <img alt="Screenshot 2021-03-11 at 10 48 47" width="850" src="https://user-images.githubusercontent.com/87168/110761343-4e75ad80-8258-11eb-8b2f-22da8f54aa48.png">
> 
> Blank canvas theme:
> <img alt="Screenshot 2021-03-11 at 10 17 13" width="174" src="https://user-images.githubusercontent.com/87168/110761368-559cbb80-8258-11eb-8dd6-03a2d29e593e.png">

The issue has been created here: https://github.com/WordPress/gutenberg/issues/29952. I'm also tracking here, and in the list of issues in the tracking issue for v10.3.x.

**Comment by WunderBart** [comment]
ℹ️ Upgraded to v10.2.1 patch.

**Comment by WunderBart** [comment]
ℹ️ Hotfixed the [missing default font for non-FSE themes](https://github.com/Automattic/themes/issues/3280) bug on Simple sites via D59109-code. Atomic sites will receive the update with the v10.3.0 upgrade.
