### ISSUE TITLE
Editor / Atomic: Block editor UI translations broken, does not display available translations

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#54217]
After a user report, I reviewed with @nellofn and @ezebecke  that there are some apparent translation issues while in the editor on WordPress.com on Atomic sites. Generally, when the Gutenberg plugin is active.

Large portions of that editor that are otherwise translated on Simple, in the standalone Gutenberg plugin, or in core are displayed in English at times. 

@ezebecke encountered a situation where having the Gutenberg plugin active seemed to resolve the issue but I've been able to consistently reproduce the issue with the plugin active. 

The standalone plugin reports 100% translation for multiple variations of Spanish and is working as expected on my self-hosted sites. https://translate.wordpress.org/projects/wp-plugins/gutenberg/ 

### Steps to reproduce the behavior

1. Access a WordPress.com on Atomic site and activate Gutenberg (it can be the WordPress.com symlinked version or the repo version).
2. Set your WordPress.com account language to Spanish (any variation)
3. Edit a post and add a Columns block for example. Inspect the block's settings and other parts of the editor. 

#### What I expected to happen

To see translated sections as I do on my self-hosted site or while the Gutenberg plugin is inactive. 

![Screen Shot on 2021-07-01 at 12:12:28](https://user-images.githubusercontent.com/4887830/124157132-7044ab80-da66-11eb-8ce7-34711d1be3a6.png)

#### What actually happened

Nearly everything is in English.

![Screen Shot on 2021-07-01 at 12:18:58](https://user-images.githubusercontent.com/4887830/124157270-9702e200-da66-11eb-8dbd-6d59ac45410d.png)

### Context

User complained of block settings note being translated, following-up via 4109172-zen

#### Does this happen on simple or atomic sites or both?

It appears Simple suffers from similar translation issues but not exactly what we're seeing on Atomic. 

#### Is there any console output or error text?

> [01-Jul-2021 15:05:06 UTC] PHP Warning:  copy(/srv/htdocs/wp-content/upgrade/es_ES-K89dPc/es_ES-81c889563f09dd13de1701135dc62941.json): failed toopen stream: No such file or directory in /wordpress/core/5.7.2/wp-admin/includes/class-wp-filesystem-direct.php on line 309

 

> [01-Jul-2021 15:05:11 UTC] PHP Notice:  WP_Scripts::localize ha sido llamada <strong>de forma incorrecta</strong>. El parámetro <code>$l10n</code> debe ser un array. Para pasar datos arbitrarios a los scripts, usa en su lugar la función <code>wp_add_inline_script()</code>. Por favor, visita<a href="https://wordpress.org/support/article/debugging-in-wordpress/">Depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 5.7.0). in /wordpress/core/5.7.2/wp-includes/functions.php on line 5313

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Likely impacts all WordPress.com on Atomic sites attempting to edit in localizations such as Spanish.  I've only tested Spanish thus far.

**Comment by JoshuaGoode** [comment]
This is known and to be expected until the Gutenberg plugin resolves issues with loading the translations in the proper text domain.

Internal notes: p1625213030060600/1625174693.060000-slack-CBTN58FTJ

**Comment by dlind1** [comment]
@JoshuaGoode With 5.8 release on Atomic sites the issue should be resolved and it looks like it in my testing, could you confirm that?

**Comment by JoshuaGoode** [comment]
@dlind1  The issue is still present from my testing and repeating the steps in my original post.

I'll try again a bit later.
