### ISSUE TITLE
[GB 11.1.0] Post Template block fatal error when rendered

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#54767]
### Steps to reproduce the behavior

1. [Create a new FSE site](https://horizon.wordpress.com/new?flags=gutenboarding/site-editor).
2. Sandbox the site.
3. View the site's front end.

#### What I expected to happen

To see the site rendered appropriately

#### What actually happened

```
Fatal error: Uncaught Error: Call to undefined function render_block_core_post_template() in wp-content/plugins/gutenberg-core/v11.1.0/lib/compat/wordpress-5.8/index.php:125
```

### Context

In the plugin, the Post Template block's renderer is defined in [`packages/block-library/src/post-template/index.php`](https://github.com/WordPress/gutenberg/blob/059339d140f7be82ce52fa4eac559678f75e5ca5/packages/block-library/src/post-template/index.php#L17).
In Core, it's in [`wp-includes/blocks/post-template.php`](https://github.com/WordPress/WordPress/blob/352fe2a88f9c87018f323e6dc33dace2e7cff50d/wp-includes/blocks/post-template.php#L17) (since 5.8).

On Dotcom, `wp-includes/blocks/post-template.php` doesn't exist.
And the function in `build/block-library/blocks/post-template.php` is renamed to `gutenberg_render_block_core_post_template`.

In support to my investigation, just simply renaming `render_block_core_post_template` in `lib/compat/wordpress-5.8/index.php:125` to `gutenberg_render_block_core_post_template` would fix the issue.

cc @scinos

**Comment by Copons** [comment]
I've added this to Cylon's board and FSE beta milestone in order to keep it tracked.
Although, I'll say that we aren't familiar with the plugin merge on Dotcom, so we'd be very very happy if this didn't land on our laps. 😄

**Comment by mattwiebe** [comment]
The short version is that we haven't finished porting 5.8 to dotcom yet so the file hosting that function is still missing. But the Gutenberg plugin still loads its 5.8 compat layer, expecting that function to be present. This should resolve itself once @david-binda finished the core merge on wpcom. See p94tqY-ps-p2#comment-1313 for more.

**Comment by mattwiebe** [comment]
The merge of the missing function was completed, this is fixed.

**Comment by Copons** [comment]
5.8 is not fully merged yet, and this issue is still happening.
I'll reopen it and wait for the full merge to close it again. 🙂

**Comment by Copons** [comment]
Looks fixed to me! Thanks @david-binda! ✨
