### ISSUE TITLE
Exporting: Intermittent issue on Simple sites

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#56810]
### Quick summary

Reported across various interactions by multiple customers (see p2EDhh-1kI-p2 for further context by @davoraltman), there appear to be intermittent issues with creating a site export on some simple sites. 

The error is present regardless of if exporting via Calypso or WP Admin screens.

### Steps to reproduce

1. Visit: `Tools > Export` on a Simple site.
2. Selected a single category under "Posts" in a specific date range.
3. Click the `Export selected content`
4. The user receives an email with the subject line "[Site name] Export failed" and the following content:

```
Unfortunately, there was an error exporting your site `Site name`.
You can try the export again, or contact us for further help.
```
&nbsp;

The email is accompanied by a warning in Calypso:

![Export error](https://user-images.githubusercontent.com/66711744/136127538-450407f8-ec7f-4b07-82f4-9f2db0717035.png)

### What you expected to happen

The export would proceed and permit a file to be downloaded.

### What actually happened

The email and error message were received instead.

### Context

I**nternal discussion:** 
p2EDhh-1kI-p2

**User interactions:**
#4346341-zen
#31845684-hc
#31845996-hc
#4325153-zen
#4346341-zen

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by inaikem** [comment]
Cc/ @msilbers @marcuswisecaesar @AtrumGeost

**Comment by pento** [comment]
Fixed in r232829-wpcom. 🙂

**Comment by Robertght** [comment]
@pento on this one 4346341-zen we're still unable to export all the content at once, but I was able to export it separately through wp-admin instead.

**Comment by pento** [comment]
Thanks for the ping, @Robertght. This is a different issue, but I'll do some digging and see what I can find. 🙂

**Comment by pento** [comment]
This new issue is fixed, the details are written up here: pcmemI-cu-p2
