### ISSUE TITLE
Press This Bookmarklet Not Working In Some Browsers

### ISSUE THREAD

**Issue by kelasante** [Automattic/wp-calypso#56960]
### Quick summary

I added `Press This` to my Bookmarks bar in Safari and Firefox, visited a WordPress.com site, highlighted text, and hit `Press This` but got a pop up to create a new post instead of 'pressing' the current page I was on. 

`Press This` worked fine in Chrome for me. However, user in  4369103-zen says it also does not work in Chrome. 

### Steps to reproduce

1. Go to Settings > Writing, drag 'Press This' to Bookmarks or Favorites bar in Safari or Firefox.
2. Visit a blog of your choice, highlight text, and hit 'Press This'. 

### What you expected to happen

I expected to be able to easily copy the post to share it to my site, like in the image below:

<img width="633" alt="Markup 2021-10-12 at 09 55 21" src="https://user-images.githubusercontent.com/74204272/136989753-24bbf84b-fb0e-46aa-881a-978bdac0289b.png">
:

### What actually happened

On Safari and Firefox, I just got a blank 'Add new post' pop up:

<img width="647" alt="Markup 2021-10-12 at 09 57 55" src="https://user-images.githubusercontent.com/74204272/136989980-934843bc-e240-444e-8b20-22a48e48b878.png">

### Context

In 28646565-hc, a user complained that Press This is no longer working on Safari, Firefox and Chrome. 

### Operating System

macOS

### Browser

Google Chrome/Chromium, Mozilla Firefox, Apple Safari

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Greatdane** [comment]
I am unable to reproduce this on either browser. Highlighting text looks to work. 

@kelasante Can you try highlighting some text on this website: https://www.lipsum.com/ and then use press this? Does it work in all browsers for you? 

Correction: Works on Firefox and Chrome, but not Safari

**Comment by kelasante** [comment]
> Can you try highlighting some text on this website: https://www.lipsum.com/ and then use press this? Does it work in all browsers for you?

@Greatdane It works only in Chrome for me. It does not work in Safari or Firefox. Here is a video of my testing in Firefox with https://www.lipsum.com/

https://user-images.githubusercontent.com/74204272/137051991-59f7b688-06da-4ca8-bbb1-b36eda7c4557.mp4

.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by jordesign** [comment]
Closing this in favor of #58098

**Comment by freelylovinglife** [comment]
Find a report here that is still not resolved ZD - 4765045

**Comment by ccwalburn** [comment]
Noting that #58098 was fixed and closed but it appears that it only resolved the issue with the bookmarklet . 
There is still an outstanding issue with the sharing button for **Press This** as reported here: 4765045-zen

**Comment by filipanoscampos** [comment]
The user on 4923078-zd-woothemes, a follow-up to 4765045-zd-woothemes, reports the issue is still affecting them.
Particularly the issue with the sharing button for Press This as reported here: 4765045-zen.

**Comment by ClassicRKR27** [comment]
Had another report of this here: [35053761-hc](https://hud.happychat.io/chat/35053761)

User provided this browser information: https://www.whatismybrowser.com/w/E94S8G5

**Comment by cuemarie** [comment]
📌 FINDINGS/SCREENSHOTS/VIDEO
- Seems the originally reported issue is regarding the `Press This` bookmark, which was closed in favor of another report, and that issue has been solved.

📌 ACTIONS
- Closed as duplicate of #58098
- Closed as no longer relevant (issue resolved by #61158)

📌 Message to Author
- I've created a separate report for the **sharing button**-specific reports moving forward. Please find that here: https://github.com/Automattic/wp-calypso/issues/67245
- If any instances of this specific issue happen again, please report them over on #58098 instead
