### ISSUE TITLE
Unable to add/edit custom color (HEX/RGB fields) on text highlights in Calypso Editor. 

### ISSUE THREAD

**Issue by Greatdane** [Automattic/wp-calypso#57687]
### Quick summary

It is not possible to enter or delete the codes in the RGB or HEX boxes when choosing a custom color in the text highlight option. 

Screenshot;
![Annotation on 2021-11-05 at 13-34-11](https://user-images.githubusercontent.com/5075840/140458696-4fabe8b2-71ff-44b6-99bb-cc31342578d9.png)

GIF:
![Screen Capture on 2021-11-05 at 12-23-23](https://user-images.githubusercontent.com/5075840/140453493-e725e0db-fc3a-4e1d-92ea-488e5a2cfd2a.gif)
 

### Steps to reproduce

1. On a page or post, enter some text in a paragraph block.
2. Highlight the text, and in the drop-down menu, choose the **Highlight** option. 
3. Choose the **Custom Color** option and toggle on **Show Detailed Inputs**.
4. Try and add or delete text from the HEX or RRB fields, it is not possible. 

### What you expected to happen

I expected to be able to type in my own custom color, or delete the HEX/RGB values via the editor. 

(Note, it is possible to paste in and the color will change without any confirmation, you can then not edit the color)

### What actually happened

I am unable to edit the HEX or RRB fields.

### Context

Customer Report. 
Atomic and Simple. This does not affect self-hosted sites who use a much more aptly named 'Text Color' option which does work. Must be a Calypso bug.

Self-hosted;
![Annotation on 2021-11-05 at 13-40-23](https://user-images.githubusercontent.com/5075840/140459116-952b3126-74fb-4a59-8e56-cc163fed646f.png)

<img width="590" alt="Markup 2021-11-05 at 13 39 27" src="https://user-images.githubusercontent.com/5075840/140459096-0f797d7e-272c-486c-b0dc-7b9b679024f2.png">

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

**Comment by Robertght** [comment]
I can replicate this as well on my end, but I'm not sure if this has been introduced with the recent release of Gutenberg.

cc @Automattic/flow-patrol-create

I asked here as well: p1636101465072700-slack-CBTN58FTJ

**Comment by MaxPhilip** [comment]
Another report in 4428337-ZD. Simple site.
Copy-pasting worked as workaround.

**Comment by alshakero** [comment]
Thanks for the great issue @Greatdane! It's so smooth to follow along and reproduce.

**Comment by WunderBart** [comment]
I can confirm that it was introduced with v11.8.0 and that it’s not WP.com specific. The custom color interface has changed and the previous one worked as expected. Here's how it looked in v11.7.1:

https://user-images.githubusercontent.com/1451471/140506874-235ffbb2-ffb1-4526-93df-07d21e11d94a.mov

**Comment by WunderBart** [comment]
Created an upstream issue https://github.com/WordPress/gutenberg/issues/36254

**Comment by cometgrrl** [comment]
This issue is tracking an issue in another repository. All +1's of end-user reports should be done on this issue, while any discussion related to the issue itself and its fix should be done on the issue in the outside repository.

**Comment by csonnek** [comment]
Also reported in https://wordpress.com/forums/topic/please-fix-the-bugs-in-the-block-editor-which-i-by-the-way-hate/

**Comment by fullofcaffeine** [comment]
This should be fixed in Gutenberg 11.8.1.

**Comment by Gustavo-Hilario** [comment]
Also reported here: 4434473-zd-woothemes

**Comment by Greatdane** [comment]
This still appears to be a bug on `Gutenberg v12.1.0-rc.1` - re-opened and added tag `Gutenberg RC Testing`

**Comment by mzitinfo** [comment]
User in 4633341-ZD reported that the issue used to be solved for some time, but now it's occurring again. They're using the copy & paste workaround now.

**Comment by darnelldibbles** [comment]
User in https://wordpress.com/forums/topic/colors-and-capitals/?view=all is also reporting the same issue is still occurring. Tried the copy and paste method as well.

**Comment by mzitinfo** [comment]
User in 4801745-ZD reports that the issue still occurs for them. (They reported it in the past already)

**Comment by kylemcph** [comment]
Another report in #4918022-zen.

**Comment by youbrokesomething** [comment]
I can't reproduce this issue and all the related Gutenburg tickets have been closed. Please reopen this if you get new user reports.
