### ISSUE TITLE
No option to reblog in the wpcom reader.

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#58089]
### Quick summary

There is no "reblog" option when looking at posts in the reader.

### Steps to reproduce

1: Open the Reader
2: Find any post that usually has sharing options

### What you expected to happen

"reblog" should be among those options.

### What actually happened

Sometime in the last hour or two, the option is missing from the reader.

### Context

Reported in 31922310-hc, and verified by me. Appears to be select blogs or select users, as some HEs still saw the option when I asked for co-testing in p1637024458323800-slack-C03TY6J1A. User reports this started in the last hour.

### Other notes

This seems to happen with simple, atomic and self-hosted sites. I tested looking at posts from self-hosted sites.

### Reproducibility

Intermittent

### Severity

One

### Available workarounds?

There is no user impact

**Comment by arinoch** [comment]
May be tangentially related to on-going issue #58073.

**Comment by roo2** [comment]
should be fixed with D70189-code. Just to confirm, this is what we should be seeing WRT reblogging in the reader right?

<img width="918" alt="Screen Shot 2021-11-17 at 3 26 06 pm" src="https://user-images.githubusercontent.com/22446385/142140271-06be10b6-9b56-43c1-9bc2-2d0c847f5cc5.png">

**Comment by arinoch** [comment]
This fixes #58073, but the option is still missing in the reader. Reopening this.

**Comment by arcangelini** [comment]
I have tested this with the same results as @roo2 I even tested using the user account who first cited this issue. Here is a screenshot of the reblog option in the Reader:

<img width="1064" alt="Markup 2021-11-30 at 19 14 48" src="https://user-images.githubusercontent.com/33258733/144104722-21f5f57c-b49e-4b44-9ea7-fc3588c757a5.png">

@arinoch can you let me know where exactly you are unable to see the reblog option specifically so I can investigate this further? Gracias!

**Comment by arinoch** [comment]
I had an opportunity to test this while investigating another issue and can confirm this was fixed and I should not GitHub after dark. Closing this on my end.
