### ISSUE TITLE
List of Pages (/pages) doesn't load on Calypso

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#59800]
### Quick summary

In the past two days, I had 3 chats where the users cannot load the list of Pages in Calypso. In all cases, I was not able to reproduce in a support session, but the user was experiencing it consistently. Browser/network troubleshooting didn't seem to affect the user's experience, but sometimes, switching devices has, but not consistently in all cases.

All users have been able to access pages through the WP Admin link, so the workaround has been switching to the Classic View from Screen Options.

Cases:

- #33499507-hc - Atomic site
- #33512661-hc / #31076589-hc - multiple simple sites, multiple accounts with the same issue
- #4645365-zen - simple site, only one site on the account affected

### Steps to reproduce

This is *only* happening with users, we haven't been able to reproduce ourselves.

1. Go to My Site > Pages on Calypso

### What you expected to happen

Calypso should show a list of pages

### What actually happened

The list of pages didn't load, but the rest of Calypso's interface loads.

### Context

Multiple customer reports

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Switching the Pages section to Classic View

### Else

cc'ing HEs who interacted with these customers: @carinapilar @galakhyati @Thelmachido

**Comment by Robertght** [comment]
Another case in #4664556-zen

**Comment by carinapilar** [comment]
Not sure if it's the same issue, but we also got a report on 31841098-hc - but for Posts, when using Firefox.

**Comment by Robertght** [comment]
Another one with Pages here: #15669416-hc / #4664803-zen

They were using Firefox 63 but even after updating the pages wouldn't show up. The drafts are visible though.

Weirdly on Chrome, their site can't be accessed at all.

**Comment by rickmgithub** [comment]
Another here - #4664723-zd

They can't access posts or pages. I can replicate this on Firefox and Chrome on my Mac.

**Comment by aleone89** [comment]
This is also starting to be mentioned on Twitter:

https://twitter.com/DimitheGreat85/status/1479072222274891778
https://twitter.com/judefire33/status/1479059429412773892
https://twitter.com/sacosw/status/1479059849854033924

**Comment by rickmgithub** [comment]
Another but on posts - #27137708-hc 

I was able to view it this time and switched to the wp-admin classic view for them which then gave them access on a browser refresh

**Comment by klimeryk** [comment]
FWIW, this has been escalated to both Calypso and Sysops and they're looking into it: p1641475924057700-slack-C02AVAR9B and p1641468811026200-slack-C02DQP0FP.

**Comment by essleeung** [comment]
I was able to see the Pages, but user can't. Potentially another case here 4664779-zd-woothemes.
Have also asked user to clear browser cache.

**Comment by aleone89** [comment]
Another report on the forums here: https://wordpress.com/forums/topic/cannot-access-posts/?view=all#post-3774681

**Comment by klimeryk** [comment]
Should be fixed now (see the p1641475924057700-slack-C02AVAR9B thread for full details). Please ask affected users to refresh (ideally, hard refresh, clean cache, etc.).

**Comment by aleone89** [comment]
This also came up the forums in the following places. 

https://wordpress.com/forums/topic/editor-wont-load-2/?view=all
https://wordpress.com/forums/topic/lochranhanratty-blog-allposts-is-not-loading/?view=all
https://wordpress.com/forums/topic/edit-my-pages/?view=all
https://wordpress.com/forums/topic/edit-process-cant-load/?view=all
https://wordpress.com/forums/topic/unable-to-edit-pages-stated-in-the-menu/?view=all
https://wordpress.com/forums/topic/unexpected-error-3/?view=all
https://wordpress.com/forums/topic/trouble-accessing-pages/?view=all

Posting just for reference.

**Comment by IoanaAMuresan** [comment]
Another instance here: 33530086-HC - today (Fri); customer could work in classic view but issue persists even when using another machine.  
(I created a ticket for following up.)
