### ISSUE TITLE
[Bug]: Reader - Duplicate comment temporarily appears when making a new comment 

### ISSUE THREAD

**Issue by brookewp** [Automattic/wp-calypso#61812]
### Quick summary

When adding a new comment to a post in the reader, a duplicate comment temporarily appears: 

![Screen Capture on 2022-03-10 at 10-13-40](https://user-images.githubusercontent.com/35543432/157729760-e72ca411-dac1-461e-9218-bad09699c0b1.gif)

### Steps to reproduce

1. Go to [wordpress.com/read/](https://wordpress.com/read/) to access Reader
2. Navigate to any posts comment section
3. Create a comment
4. See duplicate comment briefly appear 

### What you expected to happen

Expected to only see one comment appear. 

### What actually happened

A second comment briefly appears. 

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Simple/Atomic

Simple

### Other notes

Safari behaves a bit differently but it still seems like the comment is being added twice. In GIF below, wait to see second highlight to see Safari result: 

![Screen Capture on 2022-03-10 at 10-28-55](https://user-images.githubusercontent.com/35543432/157730735-3c910e09-5300-4e44-955b-883d6339654a.gif)

### Reproducibility

Consistent

### Severity

All

**Comment by tyxla** [comment]
This is a pretty interesting find, good catch @brookewp!

Seems like it's caused by the fact that we're optimistically displaying a placeholder comment when posting a new one, but we don't handle the placeholder removal immediately on successful comment / reply creation. 

Definitely an interesting one if you (or anyone else) are willing to dive deeper into Redux, the Calypso data layer, and possibly component lifecycle.

**Comment by roo2** [comment]
This may have been fixed, I see the placeholder comment appearing twice, the same as shown in the safari example but I don't see duplicated comments.

https://user-images.githubusercontent.com/22446385/202955688-fb55d65d-7cec-40b3-a611-97c0ae3ea019.mov


Tested in chrome and FF

**Comment by roo2** [comment]
I'll close this for now @brookewp , @tyxla , would either of you mind attempting to reproduce and reopining it if you can?

**Comment by tyxla** [comment]
I can still reproduce this in the comment form of a single post view in the Reader:


https://user-images.githubusercontent.com/8436925/202998735-6c5113f6-c68e-4227-9992-93fc1734866f.mov

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested in Reader

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate this. The duplicate comment appears briefly, then disappears.
- I tested using Chrome and Safari. 

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by roo2** [comment]
I'm really struggling to reproduce this. I've tried chrome safari, FF and mobile safari, I tried throttling network and CPU, I even tried in windows with browserstack. Also when I log the internal data structure "`commentsTree`", there's never a time when it contains a duplicate comment.

🤔 

@jamiepalatnik, @tyxla
 
Do you guys have any ideas or more information? I've been testing on the single post view e.g. https://wordpress.com/read/feeds/121891696/posts/4346234657

**Comment by tyxla** [comment]
It was very easy to reproduce it once more - I just did. 

I used Chrome 109.0.5414.119 (Official Build) (arm64) on macOS Ventura 13.1 (22C65) and one of my test simple sites, and just commented on the single post there, on this page: https://wordpress.com/read/blogs/200590298/posts/3 and reproduced it just as seen on the video I shared above.

No magic like network throttling or anything special was necessary. I tested on WP.com staging if that helps.

**Comment by roo2** [comment]
Ahhh thank you, I found that when I un-sandbox myself, I can reproduce it 🎉. I don't know what it is about being sandboxed that makes this go away, but it might also be a clue in how to solve it.

**Comment by roo2** [comment]
@tyxla I was able to reproduce it and created this patch https://github.com/Automattic/wp-calypso/pull/73033 I know it is not the perfect fix but I think it isn't too bad and fixes the issue as far as I can tell.

**Comment by tyxla** [comment]
Beautiful, thank you for working on it @roo2! I've left some feedback.
