### ISSUE TITLE
[E-mails] Broken site logo.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#63001]
Details in pdDOJh-fZ-p2#comment-189

**Comment by ivan-ottinger** [comment]
It looks like the issue is site-specific. I run a couple of tests with Atomic site and the Site icon loaded from `https://*.wpcomstaging.com/` domain correctly.

The site where the issue was reported on doesn't display the Site icon in General Settings:

![Markup on 2022-04-25 at 12:37:57](https://user-images.githubusercontent.com/25105483/165073859-5f3121d7-df74-448d-ba5a-23d2b97dbb4c.png)

On the other hand, the Site icon is displayed in Customizer → Site Identity:

The user could set their Site icon again in General Settings and see if that resolves the issue.

**Comment by ivan-ottinger** [comment]
I run another test with a test site where I changed the Primary address from `*.wpcomstaging.com` one to a custom domain. As soon as I made the change, the `*.wpcomstaging.com` address of the Site icon stopped working.

The cached Site icon URL (available at `https://i0.wp.com/[SITE].wpcomstaging.com/wp-content/uploads/2022/03/[SITE_ICON].jpg?ssl=1&w=240`) is still loading correctly, but as far as I know, it is just a matter of time before it gets removed (since the underlying Site icon at the `*.wpcomstaging.com` address is no longer available).

As a consequence, the Site icon will stop displaying in the General Settings and the new email templates as well.

**Comment by mashikag** [comment]
The issue was reported more than once:
- 4961613-zd-woothemes
- 4961553-zd-woothemes
- 5162594-zd-woothemes

**Comment by mashikag** [comment]
Today I investigated a bit into the 4961553-zd-woothemes issue. I tried to reproduce what the user has experienced but to no avail. 

I ran a script to send myself a "New Post" email from the user's site for the exact same post as can be seen in the user's report. However all the logos were correctly displayed to me. 

See my note on the 4961553-zd-woothemes ticket itself for more descriptive explanation of the action I took.

**Comment by villanovachile** [comment]
Regarding 5162594-zen. Thanks for looking into this and catching that! I re-uploaded the site icon in the customizer, and it is now displaying properly in Calypso, and pulling from the correct domain (not *.wpcomstaging.com). 

Does anymore testing need to be done on this site, or shall we conclude that this issue for the user should be resolved?

**Comment by mashikag** [comment]
I think the issue for the user in zen desk can be resolved, if that is what you are asking about @villanovachile. 😅 

However this issue should still remain open as it affects more than one user, and it is still not clear what is causing the issue. It is very likely other users will experience same issue in the future too until it is resolved the proper way.

**Comment by villanovachile** [comment]
> I think the issue for the user in zen desk can be resolved, if that is what you are asking about @villanovachile. 😅
> 
> However this issue should still remain open as it affects more than one user, and it is still not clear what is causing the issue. It is very likely other users will experience same issue in the future too until it is resolved the proper way.

@mashikag sorry just to clarify, it sounds like the there were two separate issues going on here:

1. The site icon was broken in Calypso due to caching of the site icon when switching primary domains.
2. The site icon is currently broken for some users in the outgoing emails (possibly unrelated to issue 1). 

With regards to this specific user, issue 1 has been resolved, however, issue 2 is likely to continue, is that correct?

**Comment by mashikag** [comment]
> 1. The site icon was broken in Calypso due to caching of the site icon when switching primary domains.
> 2. The site icon is currently broken for some users in the outgoing emails (possibly unrelated to issue 1).
> 
> With regards to this specific user, issue 1 has been resolved, however, issue 2 is likely to continue, is that correct?

@villanovachile this is correct. Issue 1 has been resolved for the user, and so the user specific issue can be closed. Re-uploading the icon fixed the issue. Caching of the site icon when switching primary domains is one way this can happen. It is very likely that this was the case for the user because I can see in their blog audit that they did connect a custom domain in the "recent" past. However my point is that this ticket can still be used to address the issue so that it does not occur for other users in the future, when they switch their primary domain. 

When it comes to point number 2 this is true that the site icon is currently broken for some other users in the outgoing emails. It is possible that the issue may be related to switching primary domains after last time the site icon was upload. It is yet to be investigated. This is why this GH ticket should remain open.

**Comment by yansern** [comment]
Issue is related to caching & changing of domain. Downtime is expected.

**Comment by yansern** [comment]
TODO: Ping someone from Atomic.

**Comment by rosepajaroja** [comment]
>2. The site icon is currently broken for some users in the outgoing emails (possibly unrelated to issue 1).

Hello there! Do we have new update on this issue #2? 

I had a similar issue here - 29132057-hc / follow-up ticket: 5458939-zen 

The domain name was changed, and it seems like the URL for the site logo on the email didn't update. 

The image URL shows - https://burgersketch.com/wp-content/uploads/2021/02/cropped-13-2.png, which is the old domain name of the site, it should have been changed to https://figjournal.com/wp-content/uploads/2021/02/cropped-13-2.png when they changed the domain name.

**Comment by ivan-ottinger** [comment]
Asked for help: p1659943600660019-slack-C4MJE0MHB.

**Comment by ivan-ottinger** [comment]
I cannot reproduce the issue anymore. Every time I change a custom primary domain on an Atomic site, the cached site icon URL changes accordingly as expected.

I suspect the underlying issue might have been fixed in the meantime. The user had probably changed their primary domain before that. Therefore their site address was still pointing to the old - incorrect address.

Taking into consideration the issue isn't replicable anymore, I am closing it. Of course, we can still reopen if there are further reports.

**Comment by happychait** [comment]
I am reopening because at least in the case @rosepajaroja reported [above](https://github.com/Automattic/wp-calypso/issues/63001#issuecomment-1207231148), the issue still persists.

I just subscribed to customer's site https://figjournal.com/ and got the following confirmation email which still shows the broken logo from the previous, removed primary domain on the site, burgersketch.com as in this screenshot: 
![Captured at 14-08-2022 at 15 47 13@2x](https://user-images.githubusercontent.com/1519466/184521654-70516060-c1df-4207-bae6-191dba0c7904.png)

**Comment by ivan-ottinger** [comment]
> I am reopening because at least in the case @rosepajaroja reported https://github.com/Automattic/wp-calypso/issues/63001#issuecomment-1207231148, the issue still persists.

> I just subscribed to customer's site https://figjournal.com/ and got the following confirmation email which still shows the broken logo from the previous, removed primary domain on the site, burgersketch.com as in this screenshot:

The way I understood this specific case was that the logo had been already re-uploaded - so I was only testing with another sites. My apologies for the confusion.

---

I have re-uploaded the logo with a different file name (via https://wordpress.com/settings/general/) and it is displaying now (added screenshot to the ticket note).

We can inform the user.
