### ISSUE TITLE
Jetpack: remove previous plan after upgrade

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6497]
We currently do not remove the existing Jetpack plan, when you upgrade your plan from premium to professional. If a user does not notice this means we may charge for each plan when the subscriptions renew.
- Navigate to http://calypso.localhost:3000/plans
- Select a Jetpack site
- Upgrade to a Premium Plan
- Complete checkout
- Navigate to http://calypso.localhost:3000/plans
- Select your Jetpack site
- Upgrade to a Professional Plan

Expected: Premium plan is removed, and professional plan is added
Actual: If you check your purchases you have both a premium and professional plan

**Comment by sirreal** [comment]
I believe this has been fixed. @gwwar can you confirm/close?

**Comment by gwwar** [comment]
👍  @sirreal this looks fixed. 

I still see that upgrading from Premium to Professional doesn't give you a discount, but that can be tracked in another issue.
