### ISSUE TITLE
Classic themes: Buttons block padding issues

### ISSUE THREAD

**Issue by sajmes** [Automattic/wp-calypso#65033]
### Quick summary

The correct padding for the buttons is being overwritten by some other CSS. This causes the buttons to display incorrectly.

### Steps to reproduce

- Add a buttons block to the page.
- The button on the published page does not show as expected. 

### What you expected to happen

The button would have the correct padding:

![Markup on 2022-06-28 at 09:21:04](https://user-images.githubusercontent.com/76757079/176189133-867562b5-50f1-4780-86ad-86f52951316b.png)

### What actually happened

The button does not have the correct padding:

<img width="2104" alt="Markup 2022-06-28 at 09 22 19" src="https://user-images.githubusercontent.com/76757079/176189447-93625b42-9353-4026-8837-d9e625842fbe.png">

### Context

5321860-zd-woothemes

When I switched the user’s site to twentytwenty-one the issue was resolved. 

### Theme-specific issue?

Hemingway Rewritten.

Possibly related to this bug for Sapor: https://github.com/Automattic/themes/issues/4019

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Greatdane** [comment]
@Robertght Question; will this issue also be fixed by p1656418840448029/1656142029.379519-slack-C02FMH4G8 and  https://github.com/WordPress/gutenberg/pull/42012/files ?

I am a little unclear if this is being caused by the issues mentioned here; https://github.com/Automattic/wp-calypso/issues/64917

**Comment by Robertght** [comment]
The padding issues with the Buttons block will be fixed in https://github.com/WordPress/gutenberg/pull/42012/files

https://github.com/Automattic/wp-calypso/issues/64917 is a report which already got a fix in 13.5.1. If everyone is ok, we can close that in favor of this one to gather the reports.

**Comment by arunsathiya** [comment]
- Quick clarifying note that https://github.com/Automattic/wp-calypso/issues/64917 is not fixed yet. 
- It will be fixed only when https://github.com/WordPress/gutenberg/pull/42012 is merged. I have made a note of that on the other issue too. 
- The current issue will be fixed by https://github.com/Automattic/wp-calypso/issues/64917 as well. Related chat: p1656579611209499/1656575923.679859-slack-C034TMVE5CM
- My suggestion is to leave the two issues independent and track reports accordingly.

**Comment by desnum** [comment]
Another case in 654050-hc using the Argent theme

**Comment by wpshellbelle** [comment]
Another report at 37241394-hc

**Comment by cuemarie** [comment]
📌 ACTIONS
- Based on the history here, I suspect this is likely fixed. I've downgraded the priority from `High` to `Normal` for now, to better reflect its status in the larger context of open bugs in this repo, and I'll retest in the upcoming weeks to see if we can close.

**Comment by gikaragia** [comment]
Tested for themes Argent and Hemingway Rewritten and the issue is now fixed. The issue still happens with Sapor it is caused by the specific theme.
