### ISSUE TITLE
New posts email notifications have incorrectly encoded subject lines.

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#65656]
### Quick summary

The new posts email notifications for a user's blog have incorrectly encoded subject lines.

Looks like accent letters like `é` is causing the issue.

Screenshot:

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/33957570/179329844-3cbddc51-04c4-4756-83b0-976726199cd0.png">

Slack: p1657881921992959-slack-C03TY6J1A

Reporting this issue as bug as suggested in the Slack thread.

### Steps to reproduce

* Subscribe to the site.
* Publish post using a title such as `Consejos exprés: La Gurrinada`
* Check the subject line in new post email notification.

I was not able to reproduce the issue on the Simple site. 

Cannot confirm if the issue is reproducible on AT site since the email notification is not working for me from my test AT site. Please see if you can reproduce this on AT site.

### What you expected to happen

The email subject line should be proper.

### What actually happened

The email subject line was unreadable.

### Context

User report: 5340719-zd-woothemes

### Platform (Simple, Atomic, or both?)

Atomic

**Comment by sharonlaker19** [comment]
I played into this ticket and ran some further tests, I was unable to reproduce on my AT site.

I tested:

- using the Classic Editor plugin.
- using the Hemingway Rewritten theme.
- using both the Classic Editor plugin and the Hemingway Rewritten theme at the same time.

The notification emails had the correct formatting in all these cases. My connection dropped for a moment so another HE played into the ticket after that. Adding my findings here for reference.

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 - No 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested on simple, Atomic, self-hosted by publishing a post with the character é. I could not recreate this issue with the notification email. The subject line displayed as expected.

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
 - @devNigel I would recommend following up with the user to troubleshoot this further. If you are able to recreate or if there are other user reports, please feel free to reopen.

**Comment by eduardozulian** [comment]
This user came back on 5507108-zen but we're still trying to reproduce the problem.

This issue might be related to #53635

**Comment by ariel-maidana** [comment]
Another case here: 5556532-zd-woothemes
Please notify the user of any update.

**Comment by paxblueribbon** [comment]
Customer reporting this: 5556532-ZD-woothemes

Of note is the fact that their posts, being in Swedish don't contain any é's but many ä's and ö's.

Please notify the user of any update.

**Comment by csabarakasz** [comment]
I have a new report like this: 

- [ ] 5604961-zd-woothemes

User does not have Classic Editor plugin activated, but they do have Yoast SEO installed right before the issue started. There are no special characters but they have `'`s in the titles.

![UDWiZutuxdpBIj6YORgeasdYcCYtCElsseVNkYsQ.jpg](https://user-images.githubusercontent.com/84539773/193914067-0a8a6594-9f6a-456e-9eee-26d3aa160cd0.jpg)

**Comment by csabarakasz** [comment]
From Logstash it seems like the ` and the ' character seems to trigger the issue in this user's case: ![nk9uhxLC2Fc72VCuSbjtloeY0i0LSETQmNkkFVyy.jpg](https://user-images.githubusercontent.com/84539773/193922257-923d8ee3-e694-4f89-af6f-17000b773d82.jpg)

**Comment by mxhassani** [comment]
Similar case here: 5649321-zd-woothemes
The problematic character, in this case, appears to be:
`ı`

The user started experiencing this after upgrading to the Business plan.

I wasn't able to replicate on my test site

**Comment by Robertght** [comment]
@Automattic/apex is this something we can get a hand with?

**Comment by druesome** [comment]
Similar issue: p9F6qB-6rA-p2

>Similar case here: 5649321-zd-woothemes
>The problematic character, in this case, appears to be:
>ı

I replied to the user and offered tips to avoid this problem by replacing the  `ı` character with `&#x131;`.  Also advised them to type the title directly into the editor rather than copying and pasting from a word processor.

**Comment by ivan-ottinger** [comment]
> https://github.com/orgs/Automattic/teams/apex is this something we can get a hand with?

Thank you, Robert! I have added the issue to our Maintenance board.

**Comment by rachelwinspear** [comment]
Another case: #5654892 

<img width="1244" alt="Screenshot 2022-10-24 at 13 23 27" src="https://user-images.githubusercontent.com/44442769/197526950-3b915bed-da05-4efe-bc4f-657804f1d7e6.png">

**Comment by aisajib** [comment]
I'm getting this on Like notifications as well. 

<img width="859" alt="Screen Shot 2022-10-26 at 5 01 20 PM" src="https://user-images.githubusercontent.com/2541844/198009825-b23cc299-a163-49d6-b18d-2239f9163eab.png">

Site: https://ais.pics/

**Comment by JuanLucha** [comment]
Hi!
I have been looking into this but I couldn't reproduce it with `ı`, nor `ö`, `'` or ```. Can I have more details about this problem, please?

**Comment by zdenys** [comment]
Here are more details from 5649321-zd-woothemes. User's post title `MARS GERİ GİDERKEN` (notice that the capital i does have a dot above, so it's not the Latin capital I that has no dot) appears as `=??Q?[Yeni_yaz=C4=B1]_Mars_Geri_Giderken?=`. 

Previously they shared that the affected letters are: ğ - ö - ü - ş - and the [dotless i](http://www.unicode-symbol.com/u/0131.html) from the Turkish language.

![J4CnYO.png](https://user-images.githubusercontent.com/39308239/198831528-7ee53476-e311-4a9c-bca4-8ea621c41f2f.png)

**Comment by mxhassani** [comment]
Another case here: 37794585-hc
![image](https://user-images.githubusercontent.com/81776920/199694541-2e9ef421-ed4e-490d-9c84-5cb29e14ceb2.png)

@Automattic/apex This appears to happen on new subscribers' welcome messages too now.

**Comment by mxhassani** [comment]
Another case here: 5680004-zd-woothemes 
The special character appear to be: `—`

**Comment by ivan-ottinger** [comment]
I tried to reproduce the issue on an Atomic test site, but without any luck. Here's what I tried so far:

- added multiple special characters / words mentioned in this thread to the post title, e.g. `ı`, `MARS GERİ GİDERKEN`, `Dil Yarası`, etc...
- set the site language and user locale to Turkish
- looked up a specific post that was sent with "gibberish" / incorrectly coded title and resent the email to my inbox from the real site using a script
- copied the content of existing post that was affected by the issue and published it temporarily on my test site

Every time, the email received was formatted correctly. 🤔 

---

> I'm getting this on Like notifications as well.

What's interesting is that in [this report](https://github.com/Automattic/wp-calypso/issues/65656#issuecomment-1291860046), the [post](https://ais.pics/yellow-green-and-an-ant/) related to this email Like notification (`Yellow, Green, and an Ant`) doesn't seem to have any special character at all, but still was affected.

**Comment by ivan-ottinger** [comment]
In case we get in touch with one of the affected users, would it be possible to ask them to forward us the email with broken site title?

We could then compare the raw email (including headers) with email that is rendered properly. That could lead us further.

**Comment by mdtanjid0** [comment]
> Another case: #5654892
> 
> <img alt="Screenshot 2022-10-24 at 13 23 27" width="1244" src="https://user-images.githubusercontent.com/44442769/197526950-3b915bed-da05-4efe-bc4f-657804f1d7e6.png">

The user came back again and confirmed the issue is resolved now.

**Comment by mxhassani** [comment]
@ivan-ottinger 
> would it be possible to ask them to forward us the email with broken site title?

There is one here: 5680004-zd-woothemes

**Comment by ivan-ottinger** [comment]
Thank you @mxhassani.

The issue is tricky in a way that we still haven't been able to reproduce it in our tests, while still seeing the issue being present for some users. We will keep digging.

**Comment by mashikag** [comment]
The issue is being addressed here: pdDOJh-15r-p2

**Quick summary**: The issue occurs when user's site has unset `blog_charset` site option and the email subject contains "special" characters. 

For more detailed explanation: pdDOJh-15r-p2

**Comment by mashikag** [comment]
The issue should be resolved now.

Resolved by: D92859-code
