### ISSUE TITLE
Videomaker White: Global Styles lacks font options.

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#66008]
### Quick summary

For the theme Videomaker White, the font family option in Global Styles Typography setting is limited. It shows only:

* Default
* Body ( Inter )
* Headings ( Inter )

Meanwhile, other FSE themes including Videomaker comes with dozens of font options.

### Steps to reproduce

1. Activate Videomaker White.
2. Go to Appearance > Editor > Styles > Typography > Text > Font family.
3. You will notice that it lacks font options.

### What you expected to happen

It should list all fonts.

### What actually happened

It didn't have options to select different fonts.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/33957570/181179376-58422ea9-ec90-4c9f-ba17-e2fccabae49a.png">

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Videomaker White

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 - no
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted - no

📌 FINDINGS/SCREENSHOTS/VIDEO
- I could replicate this with Videomaker White, but not with Videomaker, Kerr or Alonso so it appears to be specific for now.

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Added to Serenity's dashboard

**Comment by rw-ye** [comment]
User report: 5426707-zd-woothemes

Recommended Videomaker instead for now.

**Comment by csabarakasz** [comment]
new report: 

- [ ] 36376859-hc

suggested using Videomaker theme

**Comment by andres-blanco** [comment]
Relevant Slack conversation: p1660073774437949-slack-C029FM1EH

**Comment by edwinho89** [comment]
- [ ] 5480468-zd-woothemes

suggested using Videomaker theme

**Comment by sharonlaker19** [comment]
+1 in 36570544-hc

- [ ] 5496757-zen

**Comment by devNigel** [comment]
Another report: 36587545-hc

Suggested the other Videomaker theme.

**Comment by blackjackkent** [comment]
This was probably solved by https://github.com/Automattic/wp-calypso/issues/63229 - let's verify that's the case and close if so.

**Comment by NoHopeRadio** [comment]
Another report in 5546719-zen.

Another thing I noticed: even within the limited options that are there currently, they are unable to set the overall font family to the sans-serif version, and it looks like this is because there's a leftover var that got removed. Trying to set the font to the "Body (inter)" option sets the font family as `var(--wp--preset--font-family--inter)`, which doesn't seem to exist. There is a `--wp--preset--font-family--body-font` set as `"Inter", serif;` and this var is probably what should be there.

**Comment by markbiek** [comment]
@Automattic/serenity I've confirmed that this _is_ still happening. Testing on both WordPress.com and running Calypso locally with the latest `trunk`.

**Comment by arthur791004** [comment]
Looks like D85999-code doesn't work on the production because I cannot reproduce this issue on my sandbox 🤔

**Comment by markbiek** [comment]
> Looks like D85999-code doesn't work on the production because I cannot reproduce this issue on my sandbox 🤔

That's what we're seeing as well with Videomaker White _and_ [Payton](https://github.com/Automattic/wp-calypso/issues/66286).

Started a thread to discuss more in p1665499647582739-slack-C029FM1EH

**Comment by markbiek** [comment]
Thanks to @pbking for digging into this.

It seems that the issue was that the `theme.json` files had been updated but not deployed. They've been deployed and I'm now seeing the full font list for the theme.

paYKcK-2cp-p2
