### ISSUE TITLE
Some Varia Themes are Intermittently Missing from the Theme Showcase

### ISSUE THREAD

**Issue by dcoleonline** [Automattic/wp-calypso#66132]
### Quick summary

Varia and Morden do not consistently appear in the theme showcase. Other themes may be affected.

### Steps to reproduce

1. Start at https://wordpress.com/themes
2. Search for Morden or Varia
3. Even though these themes are not retired, they may not appear in the search

### What you expected to happen

I expected them to appear in the search.

### What actually happened

They don't always appear.

![image](https://user-images.githubusercontent.com/3505172/182181095-0990a1c2-efa1-4eeb-a385-51738c58a87a.png)
![image](https://user-images.githubusercontent.com/3505172/182181119-43143ee7-72f0-4e3d-bc8a-442d50729df9.png)

Sometimes Morden appears, but I haven't gotten Alves to appear.

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/3505172/182181997-36af2cfa-6c8a-4f02-805e-2f42fa5b48b0.png">

### Context

Found when working on a DIFM-L site build. The customer chose Alves and I could only activate it via wp-admin.
Also replicated by @mikeicode.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

So far, it appears to happen with Alves and Morden, but it might affect others.

### Browser, operating system and other notes

nothing noteworthy

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Visit the wp-admin theme search and activate the theme there.

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to recreate when searching for Alves, but not Morden or Varia.
- Interestingly, searching for "alve" _does_ show Alves in the search results, but the full theme name "alves" does not.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by mikeicode** [comment]
Alves again pdEkSe-YB-p2

**Comment by Robertght** [comment]
I was able to replicate this.

@Automattic/serenity can we flag this for your team?

**Comment by autumnfjeld** [comment]
@fushar @dcoleonline  Looks like this is fixed now.  Due to  the recent TS search work? 
Feature: Updates to the Theme Showcase Search and Filter pdtkmj-OF-p2


<img width="486" alt="image" src="https://user-images.githubusercontent.com/5665959/208147695-a90defe7-e7ba-4213-8612-6e6fb8ab2d19.png">

<img width="406" alt="image" src="https://user-images.githubusercontent.com/5665959/208147760-f109a003-6c54-4150-b24d-40a3a9208d57.png">

If you agree please close.

Nice job on one issue closed!! :)

**Comment by mikeicode** [comment]
@autumnfjeld Alves is still an issue. Reading the previous comments, perhaps that's the only remaining issue?

> I was able to recreate when searching for Alves, but not Morden or Varia.
> Interestingly, searching for "alve" does show Alves in the search results, but the full theme name "alves" does not.

![Screen Shot on 2022-12-16 at 11:52:09](https://user-images.githubusercontent.com/10353785/208149424-45eb9c52-3150-4173-970c-7a76ed21badd.png)

![Screen Shot on 2022-12-16 at 11:56:16](https://user-images.githubusercontent.com/10353785/208149510-e2e530a6-06de-4e4d-9d24-f615adb82d8b.png)

**Comment by aneeshd16** [comment]
I can reproduce the issue with another theme - Munchies. Searching for "Munchies" does not give any results, but searching for "Munch" shows the correct results.
![image](https://user-images.githubusercontent.com/5436027/209318637-8f920297-4333-44ac-bb38-54b92a9d0966.png)
![image](https://user-images.githubusercontent.com/5436027/209318656-70255ebb-4ee2-494f-ba0b-bc668bec152f.png)

**Comment by taipeicoder** [comment]
Fixed via D96505-code.
