### ISSUE TITLE
[Bug]: LiB with subtle pattern background pattern has broken blocks

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#68798]
### Quick summary

When I go to the site editor for a WPCOM simple site, then select Link in Bio patterns, I see this pattern that has broken blocks. After I insert that pattern, the blocks are, in fact, broken.

<img width="1385" alt="Screen Shot 2022-10-09 at 6 12 47 PM" src="https://user-images.githubusercontent.com/1126811/194783933-78d1d27c-e8f3-44ab-a480-7995e12ba2fd.png">

### Steps to reproduce

1. Create WPCOM simple site
2. Go to site editor
3. Delete all content in the editor
4. Insert the pattern
5. Verify broken-ness

### What you expected to happen

No broken blocks

### What actually happened

The opposite

### Browser

Google Chrome/Chromium

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by simison** [comment]
Debugging more (p1665391303843219-slack-dotcom-templates).

I can replicate using a new simple site, both in site editor and page editor.

Could be CSSTidy issues? Didn't test if removal in D70703-code helps.

Suggested if re-saving patterns in source site would fix at least some of the problems.

You can use e.g. https://www.diffchecker.com/ to see exact differences.

Few more patterns with similar issues. I went through all categories and found only these, but there are lots of patterns so there could be more. Symptoms all seem similar anyway.


### _Link in bio_ category

**Buttons blocks in two patterns**

<img width="400" alt="Screenshot 2022-10-10 at 14 11 22" src="https://user-images.githubusercontent.com/87168/194854810-7139a244-7c9f-4a64-bdbd-7b55368f4ba7.png">
<img width="400" alt="Screenshot 2022-10-10 at 14 10 30" src="https://user-images.githubusercontent.com/87168/194854812-603289ad-621c-4cac-a3c8-9c6fe3e5799f.png">

```diff
- <div class="wp-block-button aligncenter has-custom-width wp-block-button__width-75 is-style-outline has-custom-font has-space-mono-font-family"><a class="wp-block-button__link has-black-color has-text-color has-background wp-element-button" style="border-radius:100px;background-color:#fec997">Ep.5 Over the Rainbow</a></div>
+ <div class="wp-block-button aligncenter has-custom-width wp-block-button__width-75 is-style-outline has-space-mono-font-family has-custom-font" style="font-family:space-mono;"><a class="wp-block-button__link has-black-color has-text-color has-background wp-element-button" style="border-radius:100px;background-color:#fec997;">Ep.5 Over the Rainbow</a></div>
```

- CSS classes swapped other way around
- `style=""` got added
- one `;` got dropped out from inline styles

**Heading block**

<img width="400" src="https://user-images.githubusercontent.com/87168/194854655-cfc6ccad-c36a-4905-bad0-aa79896c7afc.png" alt=""/>

```diff
- <h2 class="has-custom-font has-text-color has-ibm-plex-mono-font-family" style="color:#dbff00;font-size:40px;text-transform:uppercase">Musician &amp; Songwriter</h2>
+ <h2 class="has-text-color has-ibm-plex-mono-font-family has-custom-font" style="color:#dbff00;font-size:40px;text-transform:uppercase;font-family:ibm-plex-mono;">Musician &amp; Songwriter</h2>
```

- `font-family:ibm-plex-mono;` appended in `style`
- classes got shuffled

### _Newsletter_ category

**Heading block**

<img width="400" alt="Screenshot 2022-10-10 at 14 09 22" src="https://user-images.githubusercontent.com/87168/194853690-a578d07f-7ea4-47bf-bad1-2f54e20548df.png">

```diff
- <h2 class="has-custom-font has-space-mono-font-family" style="font-size:2.2rem;font-style:normal;font-weight:700;line-height:1.4;text-transform:uppercase">Over 60K people have signed up. <br>Join the crowd.</h2>
+ <h2 class="has-space-mono-font-family has-custom-font" style="font-size:2.2rem;font-style:normal;font-weight:700;line-height:1.4;text-transform:uppercase;font-family:space-mono;">Over 60K people have signed up. <br>Join the crowd.</h2>
```

- Classes swapped order
- `font-family:space-mono;` appended into `style`

**Comment by ianstewart** [comment]
Should be fixed. I loaded and updated the source site pattern. (Making a separate issue to automate this.)

**Comment by simison** [comment]
> I loaded and updated the source site pattern. 

Thanks! Singular or plural, i.e. all the patterns? :-)

**Comment by simison** [comment]
@ianstewart I tested these Link in Bio patterns with a fresh simple site on Archeo theme, and still seeing the errors:

<img width="1865" alt="Screenshot 2022-10-19 at 14 06 04" src="https://user-images.githubusercontent.com/87168/196674644-7d56c276-414b-4871-b879-da7d1cececfd.png">
<img width="1815" alt="Screenshot 2022-10-19 at 14 05 41" src="https://user-images.githubusercontent.com/87168/196674652-1ae427c6-3dd9-4bd6-bae6-5776593d5500.png">
<img width="1860" alt="Screenshot 2022-10-19 at 14 05 35" src="https://user-images.githubusercontent.com/87168/196674656-acb1f243-6cef-42e0-b70b-4006788622bb.png">

**Comment by iamtakashi** [comment]
Usually, this sort of issue will come back even after resaving. I think all the ones that have the issue are the blocks that specify the font family. The issue is caused almost certainly by that.

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was not able to replicate this on an existing simple site, but I was able to replicate this on a brand new simple site created for this test. I noticed that the error message appears in the block pattern preview as well.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by dsas** [comment]
This particular pattern isn't broken, indeed all of the page patterns are currently working (_touches wood)_.

There are however, two different broken patterns. I opened https://github.com/Automattic/wp-calypso/issues/72261 for one (will reword later) and I *think* i've resolved the other, I'll monitor and open an issue tomorrow if not. See also p1674040865715699/1673918034.559799-slack-C048CUFRGFQ
