### ISSUE TITLE
FSE: Navigation Block inside footer breaks when set to display Header Navigation

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#71681]
### Quick summary

Brand new simple site: Trying to set a navigation block inside the footer to display the "Header navigation" **breaks the editor altogether.**

Existing Sites: This is also impacting users with existing menus.  We've had several users come to support today reporting that their **footer menus are missing on the live site**. We've found in all cases that the nav block in the Footer template part is not set to display the "Footer Navigation", but instead either the "header navigation", or a pre-existing menu.

### Steps to reproduce

This issue is a little tough to replicate - I had best luck in a Free empty site, to avoid pre-existing menus.

1. Create a free test site, which defaults to the theme Zoologist, and open the Site Editor.
2. Add a navigation block to the site's footer - this will create a "Footer Navigation" menu.
3. Next, add a page to the menu in the header - this will create a "Header Navigation" menu.
4. Save your changes.
5. Once you create a Header Navigation menu in your header, return to the footer, and try making the footer nav block display that menu as well.

### What you expected to happen

I expected the navigation block in the footer to display the menu I'd built in the header.

### What actually happened

The editor breaks, and returning to the editor I can't open the footer template part.

https://user-images.githubusercontent.com/27249804/210628730-4731cab3-696f-4d19-8386-3a00c89192b6.mp4

From here, if I edit the Template Part itself, I can select the Header Navigation menu as my footer's nav block.  When I return to the original template, though, it freezes again:

https://user-images.githubusercontent.com/27249804/210629185-33a92ff6-4534-40cd-9040-15928eee7f0e.mov

And on the live site, the footer's menu is now missing:

<img width="1396" alt="Markup 2023-01-04 at 11 58 18" src="https://user-images.githubusercontent.com/27249804/210629264-fbec9bad-9d71-4d37-a2d3-07391345e589.png">

### Context

User reported here: 39301919-hc

They noted this issue was not happening yesterday.  Discussion with other HEs encountering reports of the same issue here: p1672856428879729-slack-C03TY6J1A

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

FSE themes - replicated with Archeo and Zoologist, and user has reported with Tsubaki as well.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Creating a new menu in the site footer can work around the issue.

**Comment by ClassicRKR27** [comment]
- [ ] Another report here: 38151922-hc

**Comment by chad1008** [comment]
I've done some testing on this, and while I haven't yet identified exactly when it was introduced, it does look like the changes in the upcoming 14.9.x versions will address the issue.

If it hasn't already released on WPCOM before then, and/or if it's still an issue, I can work tomorrow on hunting down the preexisting introduction and fix for the bug - hopefully it's smooth sailing for affected users before then though! 😄

**Comment by cuemarie** [comment]
Another report here: 39338549-hc / 5841065-zd-woothemes (same user, just noting both for tracking

**Comment by cuemarie** [comment]
For Future HE's encountering this, you can check out some internal discussion here p1672858930739649-slack-C02FMH4G to get a sense of some troubleshooting and timing on 14.9.x , which is expected to resolve this issue!

**Comment by liviopv** [comment]
- [ ] 39356617-hc

**Comment by ccwalburn** [comment]
Another report here: 39368564-hc
Follow-up here:

- [ ] 5843375-zen

The workaround of creating a new menu did not work.

**Comment by upwardmomentum84** [comment]
Similar issue here: 39357260-hc

The user had a second Nav block in their header. The first Nav block would show on the live version but the second Nav block would not. Deactivating Gutenberg resolved the issue.

**Comment by ckmccoy2** [comment]
Similar issue here 5843627-zd / 39379470-hc

I tried creating a new menu for the header/footer (since the user only wanted to update just one going forward), but it doesn't seem to have worked

**Comment by ckmccoy2** [comment]
Not sure if this issue is related or not, but in 39360798-hc, user was trying to add menu items to their existing header menu, but they were not showing up on live site.

Worked around it by creating a new menu in header

**Comment by upwardmomentum84** [comment]
Another case here: 5842695-zd-woothemes

Menu in footer would not show. The Site Editor was freezing up as well. Manually adding the Nav block did not work. Deactivated Gutenberg allowed the menu to show and the freezing up issue stopped.

**Comment by daria2303** [comment]
5844250-zd-woothemes 

Workaround: Added another menu in the Footer.

**Comment by nerdysandy** [comment]
Reported on 5838664-zd-woothemes

**Comment by wiesenhauss** [comment]
Another case here: 5854450-zd-woothemes

Created a new menu in the site footer as workaround.

**Comment by chad1008** [comment]
This looks like it's been fixed with the release of 14.9.1 on prod sites, based on my own testing. Can anyone confirm with additional testing on another affected site?

**Comment by wiesenhauss** [comment]
> This looks like it's been fixed with the release of 14.9.1 on prod sites, based on my own testing. Can anyone confirm with additional testing on another affected site?

I tested on a Business site using the Tsubaki theme (to replicate the issue on a user site). Still not fixed (it seems 14.9.1 was not deployed on Atomic yet)

**Comment by chad1008** [comment]
Ah yes, good point - thanks for that. It won't be out yet on Atomic, but that should come later today barring anything out of the ordinary.

**Comment by darnelldibbles** [comment]
Another case here: https://wordpress.com/forums/topic/header-font-not-displaying-correctly/?view=all#post-3907084

**Comment by chad1008** [comment]
Looking at @darnelldibbles newest report, it looks like the newest version only partially fixes the issue. There were two symptoms originally:
1. Setting a footer navigation block to display the header navigation would break the editor
2. Header navigation menus in the footer weren't displayed on the live site

Testing further, it looks like the current release addresses the first symptom, but not the second. So users can _set_ the menu, but it isn't displayed.

**Future reports:** Now that we've confirmed the symptoms are more separated than it originally appeared, please include whether your report is for trouble _setting_ a header navigation menu in the footer, or if it's specifically related to the navigation block not being visible on the front end. We should hopefully only see the latter, but it'll be good to have a clear indicator of what each reporter specifically experienced!

**Comment by chad1008** [comment]
After additional testing, the `Header Navigation` menus not displaying in the footer don't appear to be WPCOM specific, so I've created an upstream ticket here:
https://github.com/WordPress/gutenberg/issues/47085

**Comment by ckmccoy2** [comment]
One more here 38700538-hc

**Comment by WunderBart** [comment]
> Header navigation menus in the footer weren't displayed on the live site

Reported happening here as well 5862586-zd-woothemes

**Comment by getdave** [comment]
Thanks for all the reports. The bug has been identified and no further reports are required.

Please see [the canonical upstream bug for details and resolution status](https://github.com/WordPress/gutenberg/issues/47085).

**Comment by liviopv** [comment]
Adding in case we want to send a mass reply:
- [ ] 5865401-zd-woothemes

**Comment by getdave** [comment]
This was fixed upstream in https://github.com/WordPress/gutenberg/pull/47453 which is scheduled to land in Gutenberg Plugin release 15.1.

Whenever that lands on Dotcom this issue should be resolved. Please ping me if that doesn't turn out to be the case.

**Comment by edequalsawesome** [comment]
I'm seeing a similar issue in 5901156-zd-woothemes (although it's for two of the same Navigation blocks in the header) -- if we send a mass reply, please follow-up with that customer in the ticket :)

**Comment by dolgelukkig** [comment]
similar issue with Bryne theme 
5904935-zd

**Comment by edequalsawesome** [comment]
Ran into this today with Varese, customer requests a follow-up when we have we have a fix through 5926555-zen

**Comment by jartes** [comment]
Another one 28556200-hc

**Comment by getdave** [comment]
@WunderBart Could you verify [the fix](https://github.com/Automattic/wp-calypso/issues/71681#issuecomment-1405422647) has landed on Dotcom and re-test? 🙏

**Comment by ccwalburn** [comment]
Another instance with Twenty Twenty-three: 5968404-zen

**Comment by happychait** [comment]
Another report in 40393150-hc

**Comment by getdave** [comment]
Ok folks I retested this on Dotcom and I _cannot_ replicate it. Nonetheless I see we are still getting reports.

@jartes @happychait @ccwalburn As this is _potentially_ a relatively major bug, please could you:

- try to narrow down the _conditions_ under which is bug occurs. Ideally screen recordings and steps.
- (if necessary) escalate the issue so that others can assist you.
- consider flagging to development teams to check that the sites in question are using the latest version of Gutenberg Plugin.

I work on Gutenberg Core and it would be really good to know that [this issue has been fixed](https://github.com/Automattic/wp-calypso/issues/71681#issuecomment-1405422647) and does not still manifest itself.

Very much appreciated 🙇‍♂️ 

cc @WunderBart

**Comment by jartes** [comment]
Hey @getdave! I tried to reproduce this on an Atomic site with the Tsubaki theme and also with a Simple Site with Zoologist theme, and I was not able to reproduce it too. 

Just noting that GB 15.1.0 was deployed on Feb 15th but reverted back to 15.0.1 due to an issue. It was finally released on Feb 16th (context p1676483487984929-slack-CB0B2G43X).

**Comment by zdenys** [comment]
I can confirm that in 5899100-zd-woothemes the AT site was using Gutenberg 15.0.1 and the Navigation block added in the footer that was using the same menu as the header was not displaying on the frontend. When I turned off Gutenberg plugin, it started showing up.

**Comment by getdave** [comment]
Thanks @jartes and @zdenys. So to confirm:

- the fix was included in Gutenberg 15.1.0.
- this was released to Dotcom but then reverted to 15.0.1 "due to an issue".
- the bug in question is [happening on sites for 15.0.1 ](https://github.com/Automattic/wp-calypso/issues/71681#issuecomment-1445144535)- that's expected as the fix is 15.1.0.

I think all we need to confirm this Issue is fixed is for someone to test a fresh AT site and confirm Gutenberg 15.1 (or greater than) is running.

## Further bug reports 🙏 

For any future bug reports please provide the exact Gutenberg Plugin version the site in question was running. 

- less than 15.1.0 - the bug will be in evidence. Upgrading to > 15.1.0 will fix it.
- great than > 15.1.0 - the bug should _not_ be in evidence and this is a legit bug.

**Comment by liviopv** [comment]
@getdave I just ran into a case of an Atomic Site using the Munchies theme where this issue still seems to be present, but in a different way. Gutenberg version is 15.3.1.

- [ ] 41326010-hc

The site has the same menu assigned to the Navigation Blocks in the Header and Footer, but in the front end, the Footer shows a different menu:

**Header Menu in the Editor**

![CleanShot 2023-03-10 at 14 49 59@2x](https://user-images.githubusercontent.com/14153300/224346767-18466919-006c-49d0-8454-cbaa2ece0896.png)

**Footer Menu in the Editor**

![CleanShot 2023-03-10 at 14 50 55@2x](https://user-images.githubusercontent.com/14153300/224346915-d29c5707-3a7d-44d6-b5d8-a909612bb157.png)

**Footer on the front end**

<img width="1439" alt="CleanShot 2023-03-10 at 14 52 57@2x" src="https://user-images.githubusercontent.com/14153300/224347418-f4c7d793-5c17-4520-912f-fc867813894e.png">

**Comment by liviopv** [comment]
@getdave I could reproduce the issue on my test site https://atlivio.wpcomstaging.com/ (Gutenberg 15.3.1) as well, both on Munchies and Twenty Twenty-Three. The results were different, though, but still broken.

Using the Munchies theme, the Footer didn't show anything in the Navigation Block, just like the original bug.

Using Twenty Twenty-Three, the Footer weirdly duplicates the footer credits:

<img width="1440" alt="CleanShot 2023-03-10 at 15 06 30@2x" src="https://user-images.githubusercontent.com/14153300/224350722-53c7e1d5-a75a-4c2d-a299-83f06235c12b.png">

**Comment by liviopv** [comment]
I couldn't reproduce it on a local site, so it doesn't seem to be a core issue.

**Comment by hacchism** [comment]
- Another report in 6056865-zd-woothemes
- AT site using Tsubaki and Gutenberg version 15.3.1

**Comment by msilbers** [comment]
reported in 41988091-hc
AT site using Gutenberg version 15.3.1
theme is Varese

they will try to create the menu manually rather than saving an existing one

**Comment by getdave** [comment]
Ok I will take another look at this in Gutenberg Core and see if I can replicate it.

**Comment by scruffian** [comment]
I think this is still a bug with the way that footer credits are inserted into the menu on WordPress.com. @fullofcaffeine, did you get any further with your investigations?

**Comment by scruffian** [comment]
I think this is still a bug with the way that footer credits are inserted into the menu on WordPress.com. @fullofcaffeine, did you get any further with your investigations?

**Comment by mpkelly** [comment]
Hi @cuemarie, it's not possible from what I can see to follow the steps to reproduce this issue. The footer block will not accept a Navigation block when I tested it. It can only accept a Page List. Therefore, I think that might have "fixed" this issue. The last support ticket was in a year ago too. 

Maybe you can retest with the Page List and then consider closing this down if it is not an issue anymore?

**Comment by cuemarie** [comment]
@mpkelly I also see that it's not possible to add a Navigation Block in the header/footer on a free test site, though I see that option on the Explorer plan of another site, which is confusing:

| free site | explorer plan |
| ------------- | ------------- |
| ![CleanShot 2024-04-22 at 10 30 06@2x](https://github.com/Automattic/wp-calypso/assets/27249804/370b5ee3-3692-4aec-b5f3-bbbc51b5b002) | ![CleanShot 2024-04-22 at 10 30 18@2x](https://github.com/Automattic/wp-calypso/assets/27249804/877c2c1b-6751-4cee-bdc4-285bb359becf) |
| Theme: TT4 | Theme: Muscat |

---

In any case, when I can add the Nav block, it doesn't look like we're defaulting to a specific "Header" or "Footer" specific navigation, so this issue does appear to be resolved through the evolution of the blocks and templates. 

![CleanShot 2024-04-22 at 10 31 13@2x](https://github.com/Automattic/wp-calypso/assets/27249804/eb8a3fb8-46f5-446e-9e79-4e17c71b5799)
_same as the nav block in the header_

I'll go ahead and close.

**Comment by cuemarie** [comment]
Ah, looks like this was resolved upstream and the issue here just wasn't closed: https://github.com/WordPress/gutenberg/issues/47085
