### ISSUE TITLE
Navigation Block: Classic Menu not updating

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#75800]
_2023-04-18 update - I actually think this is impacting all themes, not just Universal/Blockbase; and a workaround is to rearrange the items in the imported menu in the editor - that seems to force the menu to update on the live site as well. -cuemarie_

### Quick summary

[This is related to this open core report](https://github.com/WordPress/gutenberg/issues/49718), but it was suggested that I make a report for Calypso as well.

Essentially, on Universal/Blockbase themes we're still seeing an issue where selecting a `Classic` menu is able to be selected but when changes are made they do not reflect on the live site. [This was reported here](6116791-zd-woothemes) though I have seen this crop up before. I haven't been able to find any other open reports of this, but essentially this is forcing users to have to recreate their menus completely from scratch.

### Steps to reproduce

1. Select the Blockbase theme
2. Under Appearance > Menus create a menu
3. Go to the Site Editor and create a Navigation block and select the `Classic menu` that you created in step 2
4. If you try to make updates, you will not see them reflected on the live site

### What you expected to happen

The Classic Menu edits should be showing on the live site.

### What actually happened

The menu remains unchanged on the live site.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

**Comment by ClassicRKR27** [comment]
Another report here: 38618924-hc

**Comment by cuemarie** [comment]
📌 SCRUBBING NOTES

While trying to replicate, I ran into a couple variations on what you've reported, so I wanted to break those steps out here, in case they lead us down different paths.

### Simple Site Test - Did Not Replicate issue as described

- With Classic Theme `Penscratch 2` activated, I used Appearance > Menus to create a menu called "Classic Menu 2023-04-18"
- I set that menu as my header menu and saved it
- Switched to Zoologist theme, replacing homepage with theme content
- Opened Site Editor
- Selected existing Navigation block, and under **Import Classic Menu** selected my `Classic Menu 2023-04-18` menu instead, which updated in the site editor.
     - https://user-images.githubusercontent.com/27249804/232893009-276b7ac0-5fad-4659-8bf0-dc535611f468.gif
- However, when I saved and viewed the site, and no menu is visible at all in the header:
     - https://user-images.githubusercontent.com/27249804/232893377-0298b78e-ee30-4e50-881b-9f61ce20f01e.mp4
- Finally, I edited the menu, removing an item and rearranging items, and saved again, and now the menu shows.  I also returned to the editor and undid my changes, and the menu is updating according to my changes on the live site, which means this test is not replicating what is reported above.
     - https://user-images.githubusercontent.com/27249804/232894223-66aac8c0-c8f9-42b7-b78a-7ffdd17876a0.mp4

**Comment by cuemarie** [comment]
📌 SCRUBBING NOTES - CONTINUED

### Atomic Test Site - Did Not Replicate issue as described

- With Classic Theme `Twenty Twenty` activated, I used Appearance > Menus to create a menu called `Classic Menu AT Site` set to the site's "Desktop Horizontal Menu" location and saved
- I then used Appearance > Customize to create another menu called `Classic Menu AT Customizer` with the same pages, but not assigned to any location.
- Then switched to Theme Blockbase
- Opened Site Editor and replaced default menu with my `Classic Menu AT Site` menu and saved
     - The editor shows my imported menu, but the live site continues to display my previous menu
     - https://user-images.githubusercontent.com/27249804/232897028-95b9f14f-977c-41d4-8127-55db22c4c082.mp4
- I returned to the site editor and made changes to the home template and the navigation block, saved, and viewed the site again.  My changes appear, but the actual menu items are still incorrect.
     - https://user-images.githubusercontent.com/27249804/232897225-5546bb51-a217-4aa9-84b3-bc9f6064a484.mp4
- However, once I edit the imported classic menu, the updated menu then appears. Here's an example of that using my other imported classic menu:

https://user-images.githubusercontent.com/27249804/232898964-4737f251-7002-4dbf-9fa3-149496a0007a.mp4

This matches the behavior I saw in the simple site test as well - rearranging menu items (or likely other menu item changes, but **not** styles changes to the nav block) is needed to have the live site reflect the correct menu.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – [Uncertain](https://github.com/Automattic/wp-calypso/issues/75800#issuecomment-1513742493)
- Tested on Atomic – [Uncertain](https://github.com/Automattic/wp-calypso/issues/75800#issuecomment-1513766404)
- Replicated outside of Dotcom - Yes (the same behavior I could see on Dotcom - [left a commment here](https://github.com/WordPress/gutenberg/issues/49718#issuecomment-1513797599))

📌 ACTIONS
- Assigned to Cylon

📌 Message to Author
- .@ClassicRKR27 - can you review the steps I've noted above and let me know if there are discrepancies between what I've tested and what you've tested? FSE and classic menus can get confusing, so I don't want to add to the confusion ☺️
- Can you check to see if rearranging menu items allows the imported classic menu to appear on the live site as well?

Since I was able to replicate this behavior pretty consistently in Dotcom and self-hosted, I think we have enough to bring this to Cylon. But it'd be great to confirm if my tests match your experience, and perhaps we can update the original report a little to reflect those findings. Thanks!

**Comment by eduardozulian** [comment]
Got one report in 6307953-zen. Rearranging a single menu item was enough to display the menu in the site's front end.

**Comment by annezazu** [comment]
Closing this out as the related Gutenberg issue was resolved previously! https://github.com/WordPress/gutenberg/issues/49718

**Comment by happychait** [comment]
This is the closest issue I could find, so adding it here.

I just had a customer today in 9942426-zen. They updated their menu from Appearance → Menus but the newly added menu item didn't appear on the site until they updated it from the Site Editor.

**Comment by eduardozulian** [comment]
@happychait, the issue remains closed. Perhaps you'd like to reopen or move to Linear?

**Comment by happychait** [comment]
@eduardozulian Sure, I had this on my list. I noted this down here for now, as this is the best issue I could find in the time I had yesterday, but I have to find more time to report this elsewhere.
