### ISSUE TITLE
WooCommerce Mini-Cart checkout and view cart buttons not displaying when Page Optimize is active

### ISSUE THREAD

**Issue by rw-ye** [Automattic/wp-calypso#77366]
### Quick summary

The Mini-Cart checkout and view cart buttons do not show when the **Page Optimize** plugin is active along with some WooCommerce plugins such as **WooCommerce Product Bundles**.

**Error message:**

```
Oops!

Unexpected error in: woocommerce/mini-cart-footer-block

Error: Cannot read properties of undefined (reading '__experimentalUseColorProps')
```
**Video**

https://github.com/Automattic/wp-calypso/assets/21261509/3dca5a5e-ce63-4957-b92a-86f70239b218

<img width="1742" alt="Screenshot 2023-05-25 at 4 40 49 pm" src="https://github.com/Automattic/wp-calypso/assets/21261509/27452fab-210d-4efc-8825-2ef2777cbc92">

### Steps to reproduce

1. Open an AT site.
2. Install WooCommerce
3. Install WooCommerce Product Bundles
4. Activate Page Optimize
5. Activate Product Bundles
6. Add the Mini-Cart block to your site.
7. Select the Mini-Cart on the front end and you'll see the error displaying instead of the checkout and cart buttons.

### What you expected to happen

For the `View my cart` and `Go to checkout` buttons to display

### What actually happened

Error:

```
Oops!

Unexpected error in: woocommerce/mini-cart-footer-block

Error: Cannot read properties of undefined (reading '__experimentalUseColorProps')
```

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Reproduced on Storefront and Tsubaki

**Workaround**
- Deactivate Page Optimize plugin or disable **Concatenate scripts** in Page Optimize settings: `/wp-admin/options-general.php?page=page-optimize`

**Comment by rw-ye** [comment]
User report: 6326939-zd-woothemes

**Comment by rw-ye** [comment]
6323366-zd-woothemes

**Comment by carinapilar** [comment]
Another report on 6330326-zd-woothemes

**Comment by shevene** [comment]
6330454-zen

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- So far I'm unable to replicate this problem; tested with Storefront and Tsubaki. Test specifics:
     - WordPress 6.2.2
     - WooCommerce Version 7.7.0
     - WooCommerce Payments Version 5.9.0
     - WooCommerce Product Bundles Version 6.18.6
     - Page Optimize Version 0.5.3
     - PHP Versions 7.4, 8.0
     - Themes: Storefront, Tsubaki

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/98fffc5c-fa59-4e1e-bc96-96afcdfee2c9

_Went back and added WooCommerce Product Bundles Version 6.18.6 after this recording - still no issues with the mini-cart block._

📌 ACTIONS
- Requested author feedback

📌 Message to Author
- @rw-ye @carinapilar @meetshevene - are your users still seeing this issue? Can you spot anything I'm missing in my recording that may explain why this isn't replicating at the moment?

**Comment by carinapilar** [comment]
@cuemarie, the user I got had Woo’s Product Bundles active too, only worked after deactivating Page Optimize. I also had all other plugins deactivated.

**Comment by rw-ye** [comment]
@cuemarie I tried with **WooCommerce Payments** and can't replicate it now. However, I can still consistently replicate this issue with **WooCommerce Product Bundles** active. Updated the original post.

**The plugins I have active are:**

- WooCommerce Version 7.7.0
- Page Optimize Version 0.5.3 
- WooCommerce Product Bundles Version 6.18.6 


On WordPress 6.2.2 and both PHP 7.4 and 8.0

**Comment by zdenys** [comment]
6328048-zd-woothemes

**Comment by cuemarie** [comment]
Ok, looks like this was also reported here: 

- https://github.com/woocommerce/woocommerce-blocks/issues/9584

And was resolved by this fix: https://github.com/woocommerce/woocommerce-blocks/pull/9586

Having **WooCommerce Blocks** (which supports Mini-Cart) active and up to date (v10.3.0 released 2 days ago) on my site resolves the issue.

📌 ACTIONS
- Closing as fixed

📌 Message to Author/HEs
- please make sure your customers have WooCommerce Blocks installed and up to date to resolve this error!

**Comment by cuemarie** [comment]
Since Woo folks have had very busy queues, I've gone ahead and replied to all the users whose interactions were shared above and asked them to install and activate the latest version of WooCommerce Blocks to resolve the issue. 👍

**Comment by mdtanjid0** [comment]
I encountered a similar problem where the user was still experiencing difficulties. Upon investigation, I discovered that the user had not installed the WooCommerce Blocks plugin. Installing the plugin resolved the issue. This is just a heads-up.
