### ISSUE TITLE
WP 6.4 + Gutenberg are causing critical errors when editing posts on Atomic sites

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#83986]
### Quick summary

WP 6.4 + Gutenberg are causing critical errors on Atomic sites.

CLI errors:

```
PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /wordpress/plugins/gutenberg/16.9.0/lib/experimental/fonts-api/class-wp-fonts-resolver.php:208
Stack trace:
#0 /wordpress/plugins/gutenberg/16.9.0/lib/experimental/fonts-api/class-wp-fonts-resolver.php(208): array_merge(NULL, Array)
#1 /wordpress/plugins/gutenberg/16.9.0/lib/experimental/fonts-api/class-wp-fonts-resolver.php(117): WP_Fonts_Resolver::get_settings()
#2 /wordpress/core/6.4/wp-includes/class-wp-hook.php(324): WP_Fonts_Resolver::register_fonts_from_theme_json('')
#3 /wordpress/core/6.4/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#4 /wordpress/core/6.4/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/core/6.4/wp-settings.php(643): do_action('init')
#6 /srv/htdocs/wp-config.php(83): require_once('/wordpress/core...')
#7 /wordpress/core/6.4/wp-load.php(55): require_once('/srv/htdocs/wp-...')
#8 /wordpress/core/6.4/wp-blog-header.php(13): require_once('/wordpress/core...')
#9 /wordpress/core/6.4/index.php(17): require('/wordpress/core...')
#10 {main}
  thrown in /wordpress/plugins/gutenberg/16.9.0/lib/experimental/fonts-api/class-wp-fonts-resolver.php on line 208
```

### Steps to reproduce

1. Have an Atomic site running WP 6.4 with Gutenberg 16.9 active.
2.  Edit a post using the Block Editor.
3. You will see a critical error.
4. Check CLI for PHP errors.
5. Deactivate Gutenberg 16.9 - issue resolved.

### What you expected to happen

No critical error.

### What actually happened

A critical error appeared

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

Deactivate Gutenberg 16.9 and Classic Editor via CLI.

Related interactions: 
7275665-zd-a8c
7275723-zd-a8c
7275932-zd-a8c

**Comment by inaikem** [comment]
@liviopv and @Automattic/reactor for visibiltiy

**Comment by Greatdane** [comment]
7276097-zd-a8c

**Comment by ghost** [comment]
- [ ] 7276186-zen

**Comment by druesome** [comment]
7276200-zen

**Comment by ghost** [comment]
- [ ] 7276323-zen

**Comment by edwinho89** [comment]
7276361-zd-a8c

**Comment by jorpdesigns** [comment]
7276689-zen

**Comment by dragstor** [comment]
7276747-zen

ℹ️ Downgrading PHP to 7.4 seems to be fixing this somehow, for what it matters 🤔

**Comment by i11za** [comment]
7276935-zd-a8c

**Comment by liviopv** [comment]
Switching Priority to Blocker due to support impact.

There's likely another component in the steps to reproduce that we're not seeing yet. I wasn't able to replicate it on https://atlivio.wpcomstaging.com/ with GB 16.9.

What I tried:
- Publish posts and pages
- Edit posts and pages
- Switch themes (TT3 > Fewer)
- Changing fonts to a font loaded from the Jetpack Google Fonts module both from Global Styles and Block Inspector

**Comment by liviopv** [comment]
More testing:

- Switched to a classic theme - no change
- Turned on Classic Editor - no change
- When Classic Editor is active, but Block Editor is default, the block toolbar looks chunkier than usual
![CleanShot 2023-11-08 at 09 30 03@2x](https://github.com/Automattic/wp-calypso/assets/14153300/3427e2d3-4678-4388-a05f-3d9c46c7a90f)

**Comment by simison** [comment]
> When Classic Editor is active, but Block Editor is default, the block toolbar looks chunkier than usual

cc @Automattic/team-calypso-components

**Comment by rosepajaroja** [comment]
7276989-zd-a8c

Another one. Also noting that navigation to Feedback and Jetpack dashboard are also affected. 

Deactivated Gutenberg for now.

**Comment by retnonindya** [comment]
@rosepajaroja about this one: 7276965-zen -- I wonder if I missed anything. I don't see the user has AT site and the issue is on coupon code.

**Comment by retnonindya** [comment]
Sharing this on GH in case important:

I wonder if this is theme-specific considering how the issue seems intermittent. After looking at the tickets, these are the themes that the reports have:
- Pendant
- Twenty Twenty Two
- Course (third-party, but developed by A8C)
- Partdo Child (third-party)
- Hello Elementor (third-party)

For Hello Elementor, I can access the editor, so there might be something else. Other than Hello Elementor and Partdo Child (I didn’t install/activate Partdo Child on my site since it seems like a paid premium third-party theme from ThemeForest/third-party marketplace,) I can replicate the issue.

**Comment by marutim** [comment]
[7277140-zen](https://a8c.zendesk.com/agent/tickets/7277140)

Deactivated the Gutenberg plugin to fix the issue

**Comment by marutim** [comment]
7277140-zen

Deactivated the Gutenberg plugin to fix the issue

**Comment by rosepajaroja** [comment]
7277204-zen-a8c

**Comment by rosepajaroja** [comment]
> 7276965



> @rosepajaroja about this one: 7276965-zen -- I wonder if I missed anything. I don't see the user has AT site and the issue is on coupon code.

Thanks, @retnonindya! Updated it with the correct ticket ID.

**Comment by druesome** [comment]
7277667-zen

**Comment by mdtanjid0** [comment]
- [ ] 7277652-zen-a8c ( needs to follow up )

**Comment by simison** [comment]
Possibly fixed by https://github.com/Automattic/wpcomsh/pull/1544 — included in wpcomsh release v3.13.56.

Alternative fix in https://github.com/Automattic/wpcomsh/pull/1557

**Comment by Robertght** [comment]
7277723-zen

**Comment by mdtanjid0** [comment]
- [ ] 7277750-zen ( needs to follow up )

**Comment by dev-sabbir** [comment]
Another one here: 7277779-zd-a8c

Deactivating the Gutenberg plugin fixed the issue.

**Comment by simison** [comment]
Fix is being rolled out.

**Comment by Gustavo-Hilario** [comment]
- [x] 7277895-zen ( needs to follow up ). We deactivated Gutenberg on their production and staging sites.

**Comment by brinbliss** [comment]
- [ ] 7277884-zd-a8c

Deactivating Gutenberg, clearing cache, and re-activating Gutenberg seemed to immediately fix the issue. Might be related to the fix @simison was talking about?

**Comment by suyogyashukla** [comment]
7277615-zen (need to follow up)

**Comment by jenlynnemc** [comment]
7277812-zen (deactivated Gutenberg plugin)

**Comment by jenlynnemc** [comment]
7277868-zen (deactivating Gut. plugin, clearing cache and then reactivating worked for this one)

**Comment by azaozz** [comment]
> Fix is being rolled out

@simison Great! :) 

Probably worth a Gutenberg issue (maybe to check if all are arrays before that array_merge(), and eventually return early?) as it should support the `FONT_LIBRARY_DISABLED` constant as far as I see.

**Comment by simison** [comment]
> Probably worth a Gutenberg issue (maybe to check if all are arrays before that array_merge(), and eventually return early?) as it should support the FONT_LIBRARY_DISABLED constant as far as I see.

I suggested the same, and @mikachan and @priethor were already following the Slack thread (p1699420653772289-slack-C02FMH4G8) so I'll leave this to them. 👍

**Comment by mikachan** [comment]
> Probably worth a Gutenberg issue (maybe to check if all are arrays before that array_merge(), and eventually return early?) as it should support the FONT_LIBRARY_DISABLED constant as far as I see.

I was working on this earlier today when I was trying to help debug the issue, so I've gone ahead and opened a PR with what I ended up with: https://github.com/WordPress/gutenberg/pull/55974

**Comment by druesome** [comment]
7281931-zen

**Comment by simison** [comment]
> 7281931-zen

@druesome what was the issue there? This should already be resolved.

**Comment by simison** [comment]
I'll close but feel free to re-open if it's better for HE workflows.

**Comment by sajmes** [comment]
7298279-zd-a8c The user had the same issue reported here this morning, using Twenty Twenty-Two (Swiss). Deactivating Gutenberg did fix the issue for them. 

`[10-Nov-2023 14:31:49 UTC] PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /wordpress/plugins/gutenberg/16.9.0/lib/experimental/fonts-api/class-wp-fonts-resolver.php:208`

**Comment by tvolpert** [comment]
7298788-zen

**Comment by cuemarie** [comment]
Encountered 2 instances of this critical error today, with the exact same symptoms:
- Calypso shows no wp-admin links
- Editing Posts show critical error
- Editing Pages shows `User ID Mismatch`
- CLI php-errors shows:

```
PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /wordpress/plugins/gutenberg/16.9.0/lib/experimental/fonts-api/class-wp-fonts-resolver.php:208
```

In both cases, deactivating gutenberg +`cache flush` + reactivating gutenberg did not resolve the issue.

Deactivating Gutenberg and having the customer clear their cache resolved.

---

1. 7298700-zen on theme: `smithland`
1. 7299000-zen on theme `pendant-1`

Discussed further in slack -> p1699634355210049/1699420653.772289-slack-C02FMH4G8

**Comment by cuemarie** [comment]
📌 ACTIONS
- Since this is not yet fixed for all customers, going to reopen for tracking.

📌 MESSAGE TO HES
- Please note the theme slug of the theme active on your customer's site in your tracking comment. Themes may be able to get a hotfix here while awaiting a permanent fix: https://github.com/Automattic/wpcomsh/issues/1562

**Comment by ccwalburn** [comment]
7298724-zen on theme `smithland`

Deactivating gutenberg solved the issue (Deactivating gutenberg +cache flush + reactivating gutenberg did not resolve the issue)

I can recreate on my test AT site with Smithland activated; it goes away when I activate another theme (Fewer)

**Comment by simison** [comment]
New wpcomsh release v3.13.59 coming which should fix these:
```
'course',
'pendant',
'twentytwentytwo',
'smithland',
'pendant-1',
'awburn',
'nokul',
```

Please note that fix is temporary and might cause other issues, like missing fonts.

**Comment by jenlynnemc** [comment]
7300077-zen on theme ron

Deactivating gutenberg solved the issue (Deactivating gutenberg +cache flush + reactivating gutenberg did not resolve the issue)

**Comment by rinazrina** [comment]
7275307-zd-a8c on theme `twentytwentytwo`

**Comment by mgozdis** [comment]
A couple of instances yesterday. Downgraded to PHP 7.4 on both instead of deactivating any plugins. 
7299976-zd-a8c `Waverly`
7300006-zd-a8c  `Beleco`

**Comment by villanovachile** [comment]
7302373-zd-a8c `twentytwentytwo-swiss` - child of `twentytwentytwo`

**Comment by tvolpert** [comment]
7275248-zd-a8c using `twentytwentytwo`

they reported the issue on Wednesday, and as far as I can tell it's actually cleared up on their site since then, we just hadn't gotten around to responding yet.

**Comment by villanovachile** [comment]
7302626-zd-a8c `ueno`

**Comment by pauljacobson** [comment]
Reported in 7298210-zen with a follow-up in 7298251-zen

Deactivated Gutenberg to mitigate the issue.

**Comment by simison** [comment]
@pauljacobson @villanovachile could you share the theme name for customers sites as well? Thanks!

**Comment by villanovachile** [comment]
> @pauljacobson @villanovachile could you share the theme name for customers sites as well? Thanks!

Hi there

Yes, for 7302626-zd-a8c the theme was `ueno`

**Comment by arthur791004** [comment]
New wpcomsh release v3.13.60 is coming which should fix these temporarily:

```
twentytwentytwo-swiss
ueno
```

See https://github.com/Automattic/wpcomsh/pull/1566.

**Comment by jenlynnemc** [comment]
7304193-zen
Tried the deactivate, flush and activate, but that did not work, so I left gutenberg deactivated for now.
Theme was twentytwentytwo-blue

**Comment by arthur791004** [comment]
We released [another upstream fix](https://github.com/WordPress/gutenberg/pull/56067). Hence, when Gutenberg 17.0.2 is available, the issue should be resolved and we will revert the workaround (https://github.com/Automattic/wpcomsh/pull/1563, https://github.com/Automattic/wpcomsh/pull/1564, https://github.com/Automattic/wpcomsh/pull/1566) soon. See p58i-d4z-p2 for more details.

**Comment by jenlynnemc** [comment]
7306675-zen
Tried the deactivate, flush and activate, but that did not work, so I left gutenberg / classic editor deactivated for now.
Theme was Vetro.

**Comment by jenlynnemc** [comment]
7307909-zen
Tried the deactivate, flush and activate, but that did not work, so I left gutenberg / classic editor deactivated for now.
Theme was Ron.

**Comment by arthur791004** [comment]
Hi there, Gutenberg 17.0.2 is available on the atomic sites. If users still encounter this issue, we can try to upgrade their Gutenberg to the latest version to resolve this issue 🙂

**Comment by mdtanjid0** [comment]
The user, under ticket 7318641-zen, is using Gutenberg 17.0.2. Clearing the site cache did not resolve the issue, so it was necessary to keep the plugin deactivated.

**Comment by arthur791004** [comment]
> The user, under ticket 7318641-zd-a8c, is using Gutenberg 17.0.2. Clearing the site cache did not resolve the issue, so it was necessary to keep the plugin deactivated.

@mdtanjid0 It looks weird as I cannot see the fatal errors mentioned in this issue from that site. Maybe this is another issue 🤔

**Comment by radtechgh** [comment]
user reports still seeing issue after upgrade to 17.0.2. Clear site cache, deactivate/reactivate didn't help.  7318070-zen

**Comment by edwinho89** [comment]
7322181-zd-a8c

Similar as above: Gutenberg v17.0.2 still having the issue.

**Comment by arthur791004** [comment]
> 7318070-zd-a8c
> 7322181-zd-a8c

These two seem to be another issue related to the CSS Syntax, https://github.com/WordPress/gutenberg/issues/56082, as the errors are

> CssSyntaxError: <css input>:699:17: Missed semicolon
> CssSyntaxError: <css input>:58:1: Unknown word

**Comment by sudeepbaral** [comment]
- [ ] 7268530-zen

Similar issue here.
Theme: Byrne
Gutenberg Version: 17.0.2

Deactivating Gutenberg plugin fixed the issue.

**Comment by arthur791004** [comment]
> 7268530-zd-a8c

This is also the CSS Syntax issue. Could we create another issue to collect the CSS Syntax issue? Thanks!

**Comment by csabarakasz** [comment]
Many of us are seeing a CssSyntaxError with Missed semicolon that is different from this previous issue, so I created a new bug report: https://github.com/Automattic/wp-calypso/issues/84364

**Comment by arthur791004** [comment]
Thank you 💯

**Comment by mdtanjid0** [comment]
> @mdtanjid0 It looks weird as I cannot see the fatal errors mentioned in this issue from that site. Maybe this is another issue 🤔

@arthur791004 It's possible, and I apologize for not verifying the exact fatal error on the site earlier. I did notice that editing the post wasn't possible without deactivating Gutenberg. Would you like me to take a closer look and check the specific error?

**Comment by zaguiini** [comment]
@arthur791004 The CSS errors are going to be fixed with this PR: https://github.com/WordPress/gutenberg/pull/56093

**Comment by zaguiini** [comment]
@arthur791004, the PR https://github.com/WordPress/gutenberg/pull/56093 is merged. Please, whenever it gets to Atomic, verify that it fixes the problem.

**Comment by arthur791004** [comment]
Closing this issue as the critical errors mentioned at the beginning are fixed in Gutenberg 17.0.2. Another issue related to CssSyntaxError will be resolved in Gutenberg 17.2 (or possibly in 17.1.1), and we can track the errors via https://github.com/Automattic/wp-calypso/issues/84364
