### ISSUE TITLE
Purchases: When I renew cancelled purchase I can't refund it

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#845]
Steps to reproduce:
1. Purchase domain.
2. Wait 48 hours until it can't be refunded.
3. Cancel purchase.
4. Renew purchase for one additional year.
5. You will see thank you message and no option to refund.

![screen shot 2015-11-26 at 13 48 33](https://cloud.githubusercontent.com/assets/699132/11423478/0b999492-9445-11e5-9de7-a7a16972aa27.png)

Question is if I should be able to refund when I renew?

When I cancel for the 2nd time I still see blue notice with renew link:
![screen shot 2015-11-26 at 13 54 45](https://cloud.githubusercontent.com/assets/699132/11423514/624c1378-9445-11e5-83af-2b90a954c1f6.png)
When I try to renew it fails saying that I can renew only once.

**Comment by fabianapsimoes** [comment]
The same happens for subscriptions on auto-renewal, actually. It seems we're not allowing refunds for renewals in general.

**Comment by scruffian** [comment]
@fabianapsimoes - is that just for domains or for all subscriptions?

**Comment by scruffian** [comment]
I deployed a fix for this on the server just now.

**Comment by spncrb** [comment]
This is still an issue and affects plans being cancelled while domains are kept.

To reproduce:
1) Add a plan+custom domain to a site
2) Cancel the plan, but keep the domain
3) The domain shows up as "cancelled" (with no option to remove it, refund it, and renewal doesn't work as described above)

Ben thinks this is the same issue as listed above - just noting here to make sure both situations are fixed.

The fix that @scruffian  deployed was reverted by @peterbutler because it broke auto-renewals.  We need to make sure to test all noted scenarios when a new fix is created.

**Comment by fabianapsimoes** [comment]
I moved this to T302-code, since it is a server-side issue. Closing.
