### ISSUE TITLE
Checkout: Jetpack multi-year discounts are incorrect and confusing

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#87194]
### Quick summary

Jetpack now shows a "multi-year discount" line item in checkout under some scenarios, but it's either incorrect or confusing or both.

I think this was added in https://github.com/Automattic/wp-calypso/pull/86353 based on discussion in p1HpG7-qz3-p2.

### Steps to reproduce

There are two different scenarios:
1. ~Visit https://wordpress.com/checkout/jetpack/jetpack_security_t1_yearly and select the two-year option~ -- fixed via https://github.com/Automattic/wp-calypso/pull/87243
2. ~Visit https://wordpress.com/checkout/jetpack/jetpack_social_advanced_yearly and select the two-year option~ -- no longer reproducible via that product, but still reproducible via (for example) https://wordpress.com/checkout/jetpack/jetpack_ai_bi_yearly

### What you expected to happen

I'm not sure exactly, but I expected the numbers to make sense :smile: 

### What actually happened

In the first scenario above, you get this:

![jetpack-security](https://github.com/Automattic/wp-calypso/assets/235183/038efbd9-abf0-434e-95c3-a7de728ff3b3)

However, the right sidebar is problematic.  The actual introductory offer discount is the entire $191.75, not $120.  This is shown in the left column, particularly at the bottom, which makes clear that the user will pay $287.05 now and then $478.80 two years from now.

It looks like it's getting the $120 from the introductory offer associated with the **one-year** plan, and then ascribing the remaining part of the introductory offer to a "multi-year discount".  I guess that sort of makes sense, but the major problem is with the asterisk next to the $120 which says "Introductory offer first term only".  This implies that you're only going to pay $120 more next time, but that's wrong -- you're actually going to pay the full $191.75 more.

In the second scenario above, you get this:

![jetpack-social-advanced](https://github.com/Automattic/wp-calypso/assets/235183/08d8db99-f095-4bf8-8efe-16d6c27e6115)

In this case it actually is a multi-year discount ($358.80 is the full price you would pay for a one-year subscription over a two-year period), but it seems a bit confusing to me because that $358.80 number isn't shown anywhere else in checkout, so it's not clear where it's calculated from. Also, this breaks completely with the new checkout currently under development (adding `?checkoutVersion=2` to the URL) because there it doesn't show the $358.80 price, and winds up more like `$287.04 - $71.76 = $287.04`.

Fundamentally, I would also say it doesn't seem like a great idea to display an ongoing "multi-year discount" (that you can keep forever) in the exact same way that the short-term discounts which will expire (like introductory offers) are displayed?

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by DavidRothstein** [comment]
>2. Visit https://wordpress.com/checkout/jetpack/jetpack_social_advanced_yearly and select the two-year option

Worth noting that a side effect of https://github.com/Automattic/wp-calypso/pull/87109 seems to be to remove the "Multi-year discount" line **entirely** in this particular scenario (so by definition it means the issue I described won't happen).

**Comment by sirbrillig** [comment]
While I was investigating this, I noticed that it would be easy to show a "Multi-year discount" for a product whose two-year base price was different from the product's one-year price. For example, WPCom personal biennial is less expensive than 2 x the yearly price. That is clearly a discount and we could display it as such (in fact, the code I added in https://github.com/Automattic/wp-calypso/pull/87109 makes it easy to do that).

However, that's not true for Jetpack biennial: the two-year base price is exactly the same as 2 x the one-year base price. The difference is only in the introductory offer discounts, which is why this is so awkward to imply that there's a multi-year discount at all. There is not; there's just a difference in the introductory offer discount.

If we want to have a multi-year discount on Jetpack biennial, we should probably change the products' base prices to actually have one.

**Comment by eeeeeevon2023** [comment]
From what I understand **there is a discount** for paying for multiple years and that 2 year plans don't include the introductory offer. So **only 2 year plans** that also have some sort of additional discount should have the breakdown on the right. The goal is to itemize the list for users so they understand what the exact discounts are individually (instead of lumping them into one number) so they can better understand the pricing they are getting. 
@p3ob7o  @robertbpugh can you check my work here and have a look at @DavidRothstein and @sirbrillig 's concerns.  I am likely too close to this at the moment and I want to make sure I did not miss something in this design execution.

**Comment by sirbrillig** [comment]
> From what I understand there is a discount for paying for multiple years and that 2 year plans don't include the introductory offer.

@eeeeeevon2023 Unfortunately, both of those are incorrect. There is no discount for paying for multiple years for Jetpack plans, and two-year plans do still include the introductory offer. It's just that the introductory offer discount is higher for the two-year plan. 

You can see it here for Jetpack complete: the annual plan is $599.40, with a one-time discount to $299.40 (a $300 discount); the biennial plan is $1,198.80 (note that this is exactly the same as two years of the annual plan), with a one-time discount to $719.05 (a $479.75 discount).

<img width="587" alt="Screenshot 2024-02-05 at 2 08 40 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/40ed4730-35f1-4de9-9e71-7a355e8dea7f">

<img width="602" alt="Screenshot 2024-02-05 at 2 11 53 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/51030656-d2e4-4f92-9caa-22b7d6ef010b">

Compare this to WPCom plans which actually do have a multi-year discount: the annual Starter plan is R$144 and the biennial plan is R$228 (R$60 less than double the annual plan).

<img width="586" alt="Screenshot 2024-02-05 at 2 16 24 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/ec67ff37-7c6b-4be6-9449-a898e1329ae1">

<img width="584" alt="Screenshot 2024-02-05 at 2 16 53 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/175f856d-749e-432f-a811-74482549a28d">

**Comment by robertbpugh** [comment]
> There is no discount for paying for multiple years for Jetpack plans, and two-year plans do still include the introductory offer. It's just that the introductory offer discount is higher for the two-year plan.

The intent was for there to be a 20% discount for 2 year plans compared to a 1 year plan. So you're saying the way the 2 year plan was set up, it's a one time discount and not a recurring one? cc @jboland88

**EDIT - Disregard this comment, I forgot we decided to go in another direction with the discount**. pbNhbs-51x-p2#comment-15374

**Comment by sirbrillig** [comment]
Correct. At least for the biennial Jetpack plans/currencies I've tested, which admittedly isn't many. The base cost of the Jetpack Complete annual plan in USD is $599.40 and the base cost of the biennial version is $1,198.80 (599.40 x 2). Maybe that was done in error. Jetpack Security annual in USD is $239.40 and biennial is $478.80 (239.4 x 2). No multi-year discount for either.

FWIW there _is_ a discount for an annual plan vs. a monthly plan. Jetpack Security monthly is $29.95, which would be $359.4 if multiplied by 12, so that's a $10/month discount if you buy the annual plan, but you don't get much for buying the two-year plan instead.

**Comment by DavidRothstein** [comment]
Yeah, I can definitely confirm that, at least for Jetpack Security (which was my first example above).  So there may be a bug where the "Multi-year discount" is incorrectly taking into account the introductory offer prices (and shouldn't actually have been shown at all in this specific case), and then separately those products maybe have been given the wrong prices also.

For my second example above, Jetpack Social Advanced (Beta), in that case there actually currently is a discount for buying two years compared to one year (price before any discounts is $287.04 for two years and $179.40 for one year) so the issue there is a different one.

**Comment by CodeyGuyDylan** [comment]
Just adding some context, there are true multi-year discounts on some Jetpack products. Those being products without a yearly intro discount. So right now those products are Stats, AI, Search, and Social Advanced

**Comment by sirbrillig** [comment]
Thanks! I'll also note that since https://github.com/Automattic/wp-calypso/pull/87109 it's now possible to show "Multi-year discount" for any product that actually has one by altering this function:

https://github.com/Automattic/wp-calypso/blob/bee65dd930dc96483e3af7e69b0c679f40f35650/packages/wpcom-checkout/src/transformations.ts#L313

For example, if I return true for Jetpack Social Advanced in that function then I get this (although be aware that to get the math right, the "Price before discounts" is increased by the same amount):

<img width="1018" alt="Screenshot 2024-02-06 at 11 27 32 AM" src="https://github.com/Automattic/wp-calypso/assets/2036909/7af77188-90a6-4876-b835-accd1cfd85f6">

**Comment by CodeyGuyDylan** [comment]
Also FYI this is where the decision was made to structure the plans this way 😄 : pbNhbs-51x-p2#comment-15374

**Comment by sirbrillig** [comment]
Ah, that explains this a lot more. I guess maybe https://github.com/Automattic/wp-calypso/pull/86353 was really trying to highlight the one-time savings of buying a biennial plan. It's just hard to do that with the way that we display discounts. 

Maybe something simple that doesn't try to add a new line item would be best like adding subtext to the discount item like:

```
Discount for first year: -$XX
(Save $XX over one-year plan)
 ```

**Comment by robertbpugh** [comment]
> Maybe something simple that doesn't try to add a new line item would be best like adding subtext to the discount item like:

Yes. Either just have one line that says: "Introductory discount: $xxx" or you could have two lines like your suggestion.

We can move forward with this, but pause on the change for Social Advanced pending Payments team checkout v2.
cc @eeeeeevon2023

**Comment by sirbrillig** [comment]
To begin with, I'll propose removing the problematic multi-year discount for items that don't really have one: https://github.com/Automattic/wp-calypso/pull/87243

That should solve the problems described in the issue description, but I'm quite open to feedback about what to do differently.

**Comment by sirbrillig** [comment]
Since the issue is fixed, I'm going to close this for now, but we can continue to discuss how best to highlight discounts here or in other channels.

**Comment by DavidRothstein** [comment]
The first half of what I reported definitely looks fixed (thanks!), but the second half is still there since the multi-year discount is still shown for other products -- not for Jetpack Social apparently (it's now hardcoded not to?) but still for the others.

I realize I mentioned the checkout v2 behavior above but did not screenshot it, so here's a screenshot of one of the other products where you can see the math doesn't line up (this comes from visiting https://wordpress.com/checkout/jetpack/jetpack_ai_bi_yearly?checkoutVersion=2):

![multi-year-discount-v2](https://github.com/Automattic/wp-calypso/assets/235183/b759d599-a4dd-4319-ad19-0ddf1bc01707)

Arguably this should be split off to a different issue... but we don't need to fix the bug if we aren't keeping the feature, and I also want to add this to the list of checkout issues we discuss at our meetup, so I'm just going to reopen this one for now and revisit later.

**Comment by sirbrillig** [comment]
Oh, interesting. Since I removed the alternate biennial behavior but left the conditions in place to use the "real" biennial multi-year discount, it's now falling back to showing that for Jetpack biennial plans. ("real" is in quotes because there is an actual discount price difference between 2 x the 1 year plan even though it's not a discount in terms of cost overrides on the product.) That's due to this code:

https://github.com/Automattic/wp-calypso/blob/30d36ceb6b0b848547e900625956d9974c1b73e0/packages/wpcom-checkout/src/transformations.ts#L301-L305

Still, I'm not in a big hurry to remove it because it looks fine in the current checkout:

<img width="1064" alt="Screenshot 2024-02-09 at 10 58 54 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/84459492-95ef-478c-a311-299e2cac82d8">

Still, you're right that it will need to be addressed for v2. 🤔

**Comment by sirbrillig** [comment]
This should be fixed by https://github.com/Automattic/wp-calypso/pull/87400. While we can continue to discuss the usefulness of the multi-year discount as a concept, at least the math will always be correct.

**Comment by DavidRothstein** [comment]
>While we can continue to discuss the usefulness of the multi-year discount as a concept

I guess that's kind of part of https://github.com/Automattic/payments-shilling/issues/2438 now.
