### ISSUE TITLE
Subscription import: improve copy for 1 of 1

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#88855]
When publishers manually add one or a couple emails, we treat these as "import":

<img width="1507" alt="Screenshot 2024-03-25 at 16 22 08" src="https://github.com/Automattic/wp-calypso/assets/87168/f592482b-0be3-4644-b7a3-639934929451">
<img width="1513" alt="Screenshot 2024-03-25 at 16 22 32" src="https://github.com/Automattic/wp-calypso/assets/87168/d28628ab-632f-4b74-a0b2-95090f5558ac">

They aren't really adding "a list" or "importing", and particularly when they add just one email the copy looks weird with "1 of 1":

<img width="1319" alt="Screenshot 2024-03-25 at 16 22 46" src="https://github.com/Automattic/wp-calypso/assets/87168/468cd952-aa4e-442e-9f3b-7cd395b0064c">

- Do a couple of emails even need an async job and email, or would a straight API response be fast enough to do this synchronously?
- Let's use "import" and "list" language only when importing an actual CSV file, and otherwise they're "adding subscribers".
- Instead of "1 of 1" let's just spell out the email?
- Instead of "5 of 5", can we just say "your 5 emails", "your list with 5 emails", or similar? "x of y" language works when some emails weren't imported.

@crisbusquets thoughts on exact copy?

**Comment by crisbusquets** [comment]
> @crisbusquets thoughts on exact copy?

When I worked on the Subscribers Page redesign, I also reviewed the emails. This is the proposal I had (I reviewed it with Francisco and Michael at that time).

I've reviewed them again, and here's the Figma file: S4xGQTEkLhYdUvcIdn2Cfr-fi-79_13817.

<img width="1266" alt="Screenshot 2024-03-25 at 17 37 01" src="https://github.com/Automattic/wp-calypso/assets/25607244/b880f9e5-163e-4166-bb35-a7746e1ce3d5">


**Notes**
* Currently, the email we send when we can't import a large list is too long and overwhelming. I'm hoping that this proposal feels less threatening.
* I've added a `We didn’t import {Z} due to incomplete or outdated information. Ensuring quality subscribers enhances open rates and fosters a more engaged audience for better newsletter experiences`, so at least we tell them that some weren't added.

cc @zaerl

**Comment by ouikhuan** [comment]
Also cc @nerdysandy as she's working on updating the content of the email template recently. 

More context: pcmemI-2UM-p2

**Comment by simison** [comment]
Cool, good timing. @nerdysandy can you please work with @crisbusquets to review the copy you might already have, and how it works with the [copy above](https://github.com/Automattic/wp-calypso/issues/88855#issuecomment-2018441431) from @crisbusquets ? Thx both!

**Comment by ouikhuan** [comment]
@zaerl and I were talking about how we are going to do with email validation( p1711439208888539-slack-C01A60HCGUA ), and we think it might be a good idea to provide some details and hopefully reduce some HE support volumes as well. Would love to continue the discussion in the P2 or Slack discussion if you're interested in it!

**Comment by zaerl** [comment]
Steps to perform:
1. Update text of `subscribers-imported` template in the `jetpack` theme
2. Remove the `subscribers-imported` template from the `calypso` theme and create a new one with the same name inside the wpcom-2022 theme

**Comment by zaerl** [comment]
The Bkismet notification has been removed. Context: p1711440282001509-slack-C01A60HCGUA

**Comment by bogiii** [comment]
Done here: D143481-code

**Comment by ouikhuan** [comment]
I think we're still missing a case where users pass the spam check but non of the emails got imported, I know @nerdysandy is working on this, you can find more context here: ( pcmemI-2UM-p2 ) @nerdysandy, by looking into the Figma file ( S4xGQTEkLhYdUvcIdn2Cfr-fi-79_13817 ) , it feels like it falls into the "Something went wrong" template. Is that correct?

cc @crisbusquets

**Comment by bogiii** [comment]
Done: D143481-code
