### ISSUE TITLE
Signup: Checkout sidebar

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#900]
When signing up for a new site with a paid plan, the sidebar overlaps the checkout if your browser is around 900px wide:

<img width="941" alt="screenshot 2015-11-27 16 46 30" src="https://cloud.githubusercontent.com/assets/275961/11445740/a641a58e-9526-11e5-8996-c24c34bcca7e.png">

cc @shaunandrews

**Comment by breezyskies** [comment]
Looks like this was fixed in https://github.com/Automattic/wp-calypso/issues/1005. Closing.

**Comment by scruffian** [comment]
Still broken for me in Firefox:
<img width="1427" alt="screen shot 2016-01-12 at 11 14 44" src="https://cloud.githubusercontent.com/assets/275961/12262197/4270a49e-b91e-11e5-96e1-6d4f9a7aed61.png">

**Comment by shaunandrews** [comment]
So, if you visit the page directly (with a url like https://wordpress.com/checkout/sitenamegoeshere.wordpress.com) all is well in the world. When you go through the signup flow, the 'has-no-sidebar' class name isn't being removed:

![screen shot 2016-01-21 at 11 57 50 am](https://cloud.githubusercontent.com/assets/191598/12487697/45854eb8-c036-11e5-86a5-22cf946fcb5d.png)
