### ISSUE TITLE
Components: Flag icon on Phone Input component poorly rendered on IE11

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#9382]
#### Steps to reproduce
1. Using IE11, open URL: https://wpcalypso.wordpress.com/devdocs/design/form-fields
2. Scroll to the Form Media Phone Input section

#### What I expected
To see the flag icons the same as in other browsers.  Chrome is pictured here:
![screen shot 2016-11-15 at 8 33 32 am](https://cloud.githubusercontent.com/assets/7233112/20307592/37e57198-ab0e-11e6-9d4a-2dfcb54dc7b9.png)

#### What happened instead
Various different rendering problems based on country:

USA:
![screenshot 8](https://cloud.githubusercontent.com/assets/7233112/20307631/5491abfe-ab0e-11e6-975c-420ac0a72664.png)

Armenia:
![screenshot 9](https://cloud.githubusercontent.com/assets/7233112/20307643/59d63f1c-ab0e-11e6-828f-bfb1b9ab7788.png)

All other browsers checked out fine (Chrome, Firefox, Safari, Edge).

cc: @umurkontaci #7456

#### Browser / OS version
Windows 10 IE11

#### Context / Source
#automated-testing #visdiff

**Comment by umurkontaci** [comment]
Wow IE. That's some serious rendering skills.

Thanks for the report!

**Comment by umurkontaci** [comment]
This was fixed in a PR that I can't remember which.

**Comment by hoverduck** [comment]
@umurkontaci I'm still seeing the problem in my Windows 7 IE11 install...exact version 11.0.9600.18163.  I also see the same thing via Browserstack, so it's not just my machine.
