### ISSUE TITLE
Business Plan Site Creation Fails

### ISSUE THREAD

**Issue by robertbpugh** [Automattic/wp-calypso#93876]
### Quick summary

When I try to create a new site with a business plan, the site creation cycles forever.

Video and discussion here: p1724440244700419/1724437677.558359-slack-C029GN3KD

### Steps to reproduce

Incognito Chrome, logged out. 1) LOHP -> Click Get Started 2) Log in non a11n account 3) skip domain search 4) choose business plan

### What you expected to happen

Create a business plan

### What actually happened

Cycles forever

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by agrullon95** [comment]
Resolved with: https://github.com/Automattic/wp-calypso/pull/93883

**Comment by alshakero** [comment]
Reopening as it was not resolved. We shouldn't redirect to /setup/onboarding.
