### ISSUE TITLE
The Discover feed incorrectly bumps up old content as current

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#95739]
### Quick summary

The number one post from my feed says it was posted 3 days ago

![Image](https://github.com/user-attachments/assets/6db71415-65ad-43a1-ab76-729bf7b3cb96)

However, clicking reveals that the post is at least 8 years old and gets its date updated for more views

![Image](https://github.com/user-attachments/assets/dc223ec2-1022-4d17-b4a7-b0a5dc562d82)

### Steps to reproduce

The way I discover such cases is by liking the discover feed and then coming back a month later to find some of the post I liked on top of my feed.

You may need to go over the list of and find one such post yourself.

Here's one:
https://wordpress.com/read/blogs/28958452/posts/29963

### What you expected to happen

Posts from 2016 should not go to the top of the feed when their publish date is changed.

### What actually happened

People can trick the system and bump their content to the top of Discover once their post is approved to be there.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

This is a data issue, however I couldn't find a better place to report it.

### Platform (Simple and/or Atomic)

Simple

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Reader – Could Not Replicate 


📌 ACTIONS
- Requested author feedback

📌 Message to Author
- @dzver I'm unable to replicate this on my end and the link above points to something else, but while checking the post itself, I cannot see what the user has done exactly. 
- @Automattic/loop I can see this is already in your Inbox so please let us know if there's anything in particular we can help in the process.

**Comment by davemart-in** [comment]
Thanks. I marked this as high priority.

**Comment by dzver** [comment]
Top result on /discover today is from 2016

https://github.com/user-attachments/assets/c42bf1a1-74cc-4641-a738-723ffcffd4a0

**Comment by dzver** [comment]
<img width="781" alt="Image" src="https://github.com/user-attachments/assets/31c4914e-f870-4045-8bcf-47d1cecff9f7" />

**Comment by davemart-in** [comment]
Yeah, there is likely some intentional manipulation going on here. Is it possible to see when a post was originally published and exclude posts from discover where the publish date is manually being updated? 

Thoughts?

cc @holdercp, @eoigal, and @spsiddarthan

**Comment by dzver** [comment]
<img width="775" alt="Image" src="https://github.com/user-attachments/assets/2f90c303-059f-4898-9fe6-628e567a1080" />

This morning the /discover feed features 7 consecutive articles by one site.
https://wordpress.com/read/feeds/145925

**Comment by spsiddarthan** [comment]
>Yeah, there is likely some intentional manipulation going on here. Is it possible to see when a post was originally published and exclude posts from discover where the publish date is manually being updated?

I am yet to understand how the discover posts algorithm works, but from a WordPress perspective, `wp_get_post_revisions` will help us get the first published date. I am not yet sure about the scalability concerns around calling wp_get_post_revisions for each post, I will try and get my head around the discover algorithm and see if there is a better way to do this.

**Comment by spsiddarthan** [comment]
I looked at this some more today. Using `wp_get_post_revisions` may not be the post performant thing to do here. I learned about this core field `_wp_old_date` which gets populated whenver the publish date of the post changes. All WPCOM posts have it ever since it was made available in core, but for Jetpack sites, the `_wp_old_date` meta is not being sycned to WPCOM. 

I have asked the sync folks about whether they are ok with syncing this field to WPCOM - p1734421127891699-slack-C0836HR68MV. If they agree, my approach would be add this metadata to the post object in `WPCOM_JSON_API_Read_Site_Post_Endpoint` and then, filter older posts at the streaming level. 

I will share an update once I hear back from the sync posts.

**Comment by spsiddarthan** [comment]
The Jetpack folks are happy with syncing the _wp_old_date post meta field.

I have begun working on a solution [here](https://github.a8c.com/Automattic/wpcom/pull/168973), but I have hit a stumbling block with the StreamFilters which I haven't managed to solve yet. I will have to spend some more time on it, but I feel the direction I am moving in is correct. The linked PR has more details and I have begun a discussion on our team channel here - p1734522190373659-slack-C0836HR68MV

I am going on AFK from tonight, so I can continue looking at this when I am back. I am unassigning myself temporarily in case someone else wants to take a look while I am away. I can return after my AFK and take it forward should no one else get to it before me.

**Comment by spsiddarthan** [comment]
I am looking at this again, and I am working on a solution to not show posts whose dates were modified with the intention of making the post rank high in recommendations.  I am getting close and should have a solution for this in a day or two. I needed to understand how the streambuilder library worked.

>The families post is still there. Tagging it because no matter if we check the post revisions, it should not just stay there for one week. Make it go away if I like it :)

@dzver, I agree with you, but I thought I will address this issue separately. Are you suggesting if you like any post that shouldn't appear in your discover feed again?

**Comment by dzver** [comment]
<img width="815" alt="Image" src="https://github.com/user-attachments/assets/4ed847de-d8e6-4da0-a88b-07698b8c8093" />

Not sure what's going on, there posts were not bumped but are really old and appear in the feed.

**Comment by dzver** [comment]
Also, the /discover feeds ends after showing about 50 posts, 15-20-ish of which are 1+ years old.

**Comment by spsiddarthan** [comment]
This should be fixed now, we shouldn't see posts that are old in the feed either through manipulation or otherwise. 

I plan to look into the specifics of how ES recommends posts and also analyze the ES queries next. I will publish my findings in a p2 post. I will make sure to copy you on it @dzver

**Comment by dzver** [comment]
The discover feed looks much better now. Actually, I think I started getting some views from it on my personal blog.

It's still not doom-scroll quality because it shows posts up to 2 weeks old, which means that if I browse the feed going back to page 10, I'll likely see the same posts over the next 4-5-6 days, with new posts appearing here and there. But it's a major improvement.

**Comment by dzver** [comment]
I'm afraid the nightmare of Elm street is back.

<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/8d05c258-c1af-466b-8fd0-d5a3d017bd08" />

**Comment by dzver** [comment]
@spsiddarthan apologies for reopening it but this is the worst form of the problem, a 2016 post that I first liked years ago is bumped to number one in the feed.

**Comment by spsiddarthan** [comment]
Thanks for reopening, I will debug it.

**Comment by spsiddarthan** [comment]
I found an annoying problem with data formatting. There are two types of data streams and the filter was getting applied only on one of them. I am just testing my fix.

**Comment by spsiddarthan** [comment]
@dzver, should be fixed now. Hopefully, it stays that way and there are no more surprises.

**Comment by spsiddarthan** [comment]
Whenever such posts appear in the feed, they should get filtered out and we are logging it to logstash. I will keep an eye on that as well to ensure this continues to work.

**Comment by dzver** [comment]
Thanks, I appreciate the quick resolution! I didn't expect you to work on Saturday to fix that, we could've endured another day or two with the Families post :)

**Comment by spsiddarthan** [comment]
Of course :) I was just checking my emails and thought I might have a quick time boxed session to see if I could resolve it.

**Comment by spsiddarthan** [comment]
This seems fixed, I reckon. Closing it, but feel free to reopen if it reappears.
