### ISSUE TITLE
Help Center: appears pre-opened when SUing to a user session (happens for specific accounts)

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#99073]
### Context and steps to reproduce

When SUing to a user account, the help center appears pre-opened in the SU'd session. It started happening to a few HEs (p1738116381559419-slack-C03TY6J1A) on Jan 29. I have tested with several accounts, but I see this behavior only on a few accounts. 

![Image](https://github.com/user-attachments/assets/2f1374c8-62c6-4609-87a9-21cf0a3b6db7)

The ones I've noticed it have either only simple sites, only Atomic sites, or a mixture of two, so is not site-dependent.

### Site owner impact

Between 20% and 60% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

No revenue impact

**Comment by arunsathiya** [comment]
One example where I've noticed it - 9341447-zen

**Comment by le-sgs** [comment]
This still happens and another example of where I've noticed this: 9352009-zd-a8c.
I see this more on simple sites too.

**Comment by khristiansnyder** [comment]
I've been seeing this issue quite a bit the last several days:

![Image](https://github.com/user-attachments/assets/ab43f061-fbb6-404b-a321-76d51b451314)

**Comment by philnick206** [comment]
I'm seeing this consistently on most/all sites I SS into:

![Image](https://github.com/user-attachments/assets/361e872e-cae9-4ec9-b322-e3bc9d3024e2)

**Comment by Robertght** [comment]
I'm seeing this super frequently now.

@Automattic/vertex is this something you could help us with? 

I'm raising this as a High priority as it's interfering with our workflows.

**Comment by escapemanuele** [comment]
Hey @Robertght do you see it still happening? We should have pushed a fix not long ago.

**Comment by alshakero** [comment]
Should be fixed in Calypso, Simple, and Atomic sites now.

**Comment by desnum** [comment]
Yesterday I experienced the issue in 9353421-zd, 9353444-zd, 9353531-zd, 9353590-zd, 9353656-zd, 9353651-zd, 9354343-zd, 9354393-zd, 9354459-zd, 9354508-zd, 9355359-zd

**Comment by khristiansnyder** [comment]
Still running into this today, such as in  #9364881-zd

Dashboard pages open with Help Center expanded: 

![Image](https://github.com/user-attachments/assets/487248c9-bd93-4b0f-a41f-bfcf4800e6ce)

**Comment by khristiansnyder** [comment]
> Hi [@khristiansnyder](https://github.com/khristiansnyder)! Why do you mean by dashboard? Is it wp-admin or my home?

So far I notice the help center expanded in some WP-Admin dashboard pages when accessed. I've had a couple today and will try and update with instances I come across.

**Comment by arunsathiya** [comment]
>So far I notice the help center expanded in some WP-Admin dashboard pages when accessed. I've had a couple today and will try and update with instances I come across.

Yeah, that happened to me on my own website as well.

**Comment by khristiansnyder** [comment]
@alshakero An example from just now, after logging into a site, clicking Posts launches the help center. Atomic site: #9372895-zd

**Comment by alshakero** [comment]
Fix is here: https://github.com/Automattic/wp-calypso/pull/99304

**Comment by alshakero** [comment]
Fixed now. Please let me know if this happens again. It 99.99% will never happen again.

**Comment by arunsathiya** [comment]
@alshakero I ran into two cases today, although I do not have the blog IDs or Zendesk IDs. In both the cases, it was an Atomic site SSO'd into the wp-admin dashboard, not SU or SSP. Would that be an edge case that we are not looking into yet?

**Comment by alshakero** [comment]
Unfortunately, if it happened once, it may happen again. If it happens again I'll have to build a much more complicated solution. So let's give it one more chance.

**Comment by le-sgs** [comment]
I also ran into this two times today. Here's one such ticket: 9379499-zd-a8c

**Comment by khristiansnyder** [comment]
Thank you for your work on this! It happened again for me just now: #9381790-zd

**Comment by alshakero** [comment]
OK. I'll modify the support-session plugin to fix this.

**Comment by arunsathiya** [comment]
I appreciate your ongoing efforts to resolve this issue. I've had a case this morning though on a SSO'd session, [just like earlier](https://github.com/Automattic/wp-calypso/issues/99073#issuecomment-2636964026). Are SSO sessions not considered proxied for some reason?

**Comment by alshakero** [comment]
Thank you, Arun. They definitely are. Could you share the ticket?

**Comment by arunsathiya** [comment]
I mean, it's very easily reproducible on any test account's Atomic site's SSO'd session (SSO from user RC). I can find some ticket IDs tomorrow though, and possibly share a video recording of the issue too.

**Comment by Robertght** [comment]
I didn't see this issue anymore in the last several days so I believe this is fixed for good.

Thank you @alshakero!

**Comment by arunsathiya** [comment]
This is still happening, consistently, but only for customer accounts that have reached us on live chat. Example - 9407285-zen

![Image](https://github.com/user-attachments/assets/29a5fc9a-308c-4fe7-9526-2b0197285ac8)

If you create a new test account without a support contact yet, and SSO into its Atomic site, you wouldn't see the issue though. So, you need to test against a customer that has contacted us recently.

I am in the minority, as most of the staff use SU instead of SSO.

**Comment by Robertght** [comment]
I found another one here 9412763-zen

@alshakero I'm going to reopen this for now, but let us know if there is something we missed in the process.

**Comment by alshakero** [comment]
Aah I missed the `and SSO into its Atomic site,` part! This can be it. I'll look into it.

**Comment by philnick206** [comment]
This is still happening for me, and I'm using Support Session. It just occured when I SS into the site in 9433584-zd-a8c

![Image](https://github.com/user-attachments/assets/e39e3532-bc1c-4bab-bfca-5efa0a6673d8)

**Comment by aisajib** [comment]
Realized I haven't logged a case here, but I run into it frequently in nearly every time when I SU.

**Comment by heavyweight** [comment]
We identified a case where SSP is used. 
On calypso pages the checks that are in place fail since they assume the html added by the support session plugin will be there.
But this is not the case, there is no support session bar. The interface is indistinguishable. 

Are you SUing from the user's report card or using the SSP?

**Comment by aisajib** [comment]
> Are you SUing from the user's report card or using the SSP?

Hi! Not sure if you were asking anyone specifically, but I have been using Switch to user option (with the browser extension on Chrome). I don't have a screenshot now, but I see what the OP shared in the original issue (with an orange support session bar). 

I see that orange support session bar is missing in one of @philnick206 's screenshots above. Nick, do you use a script to change the admin bar color or were you SSP-ing?

**Comment by heavyweight** [comment]
Just deployed a PR related to this.
We have SSP check now plus one more additional check for support sessions.
Let me know if you have any issues

**Comment by arunsathiya** [comment]
Unfortunately, this is still happening on "SSO" (not SSP or SU) sessions. You can try it on the site associated with this ticket - 9458168-zen

<img width="706" alt="Image" src="https://github.com/user-attachments/assets/8f9f3c3f-64be-459c-961d-71ed45a08dd2" />

To access via SSO - please navigate to the user RC and click on the SSO button on the left.

**Comment by arunsathiya** [comment]
Also happening with SU sessions on Google Chrome - 9462866-zen (Atomic site)

![Image](https://github.com/user-attachments/assets/dc19ee57-65b7-4c19-be4c-e23d4d8136ce)

**Comment by arunsathiya** [comment]
This hasn't happened in the last 7-10 days. Not sure what changed between then and now, but it seems to be resolved, at least for me.
